### PR TITLE
Update srp.index Vodafone Germany and DVB-T2 BER

### PR DESCRIPTION
**Pull request by 4l3x2k**
The DF1 logo is only HD, but there is also a SD channel. So removing the logo for SD channel.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Which logo are you wanting to remove and why? Surely you leave the logo alone and  just remove the link that uses it to create a picon. Unless the logo is not used by anything else.

**Comment by Lexzie** [comment]
No logo have to be removed.
I need to make a SD logo for DF1.
Since there was only an HD version on satellite I only made that one.
I can possibly do that this evening.

**Comment by AbuBaniaz** [comment]
@Lexzie 
Please merge this if OK https://github.com/picons/picons/pull/2006

**Comment by AbuBaniaz** [comment]
We now have a `df1` logo. Please add the link to use it in your pull request.

**Comment by 4l3x2k** [comment]
Yes, like @Lexzie had explained. There is no logo to be removed. Only the channel ref for DF1 in SD has beed removed and is now readded with the correct logo.

**Comment by AbuBaniaz** [comment]
I went by your comment.

 What you meant was delete an incorrect/changed assignment/linkage. Nothing to do with logos.

**Pull request merged**
