### PR TITLE
New and improved slam! logos

### PR DESCRIPTION
**Pull request by Varkentjes**

### CODE REVIEW

**Comment by Lexzie** [comment]
Looking good, although I still see white pixels om the edges of slamhardstyle and slamjuize logos.
Paint all the edges black and after that make the light logo.
I hope you are able to do so.

**Review by Lexzie — CHANGES_REQUESTED** [review]
Looking good, although I still see white pixels om the edges of slamhardstyle and slamjuize logos.
Paint all the edges black and after that make the light logo.
I hope you are able to do so.

Just a few (not all) pointed out what I mean (zoom in to see the bad pixels):
afbeelding
And a you clearly see, the edges of the SLAM! logo.

  
And I knowm it's a lot of work, but it pays of in the end that we have the best logos!
  

And did I mention that I appreciate very much what you are doing?

**Comment by Varkentjes** [comment]
Yea these two logos are annoying. But I couldn't find any better so I have to deal with it. I completely redesigned the other logos as you advised me.

I will fix the issues soon.

**Comment by Varkentjes** [comment]
Mentioned logos are modified, also a missing link for slam summer added.

**Comment by Lexzie** [comment]
Great work, I'm impressed.

**Pull request merged**
