### PR TITLE
Update France Logo

### PR DESCRIPTION
**Pull request by Hbt-Pierre**
Hi,
I updated some icons from France Package Canal+ / Canalsat including  _TF1, M6, BFMTV, NRJHITS, M6MUSIC._
I also edited srp.index. 
Two channels (_RMC Sport 3 and 4_) didn't have the right service id. 

And finialy I added a logo for _MTV MUSIC 24_ which used _MTV MUSIC_ logo.

### CODE REVIEW

**Review by mrhotio — CHANGES_REQUESTED** [review]
Failed checks need to be resolved and commit messages in English.

**Comment by Lexzie** [comment]
Your errors are generated because you're adding a png while there's still a svg present.
To avoid that you should delete the old ones too.
But read this below, because I found for all your png's svg-files:

**bfmtv.default.png**
Furthermore: Please edit, clean and add the svg simply found here: https://www.bfmtv.com/assets/images/BFMTV.svg

**histoire.default.png**
We already have that logo, it's called `histoiretv`.
You could replace it by this svg: https://static.wikia.nocookie.net/logopedia/images/8/80/Histoire_TV_%282019%29.svg/revision/latest?cb=20200314110416

**m6.default.png**
Please use svg! I found it within a second: https://commons.wikimedia.org/wiki/File:M6_1987_logo.svg

**m6music.default.png**
The logo you want to commit is of terrible quality.
Please use this svg: https://static.wikia.nocookie.net/logopedia/images/6/68/M6music-95cde0867d.svg/revision/latest?cb=20200412210630

**mtvhd.light.png**
The current one needs to be corrected indeed. But we already have a svg, please correct that one.

**mtvmusic24.default.png**
Please use the svg available on Logopedia: https://static.wikia.nocookie.net/logopedia/images/5/59/MTV_Music_24_%28Poland%29.svg/revision/latest?cb=20200724030851

**nrjhits.default.png**
Please use svg: https://upload.wikimedia.org/wikipedia/fr/3/36/NRJ_Hits_2017.svg

**tf1.default.png**
Please use svg: https://upload.wikimedia.org/wikipedia/fr/7/77/TF1_%282013%29.svg

If you're not up to the task I will help (because I don't want bad logos).
But if you can doi it that saves me time!

**Review by Lexzie — CHANGES_REQUESTED** [review]
Your errors are generated because you're adding a png while there's still a svg present.
To avoid that you should delete the old ones too.
But read this below, because I found for all your png's svg-files:

**bfmtv.default.png**
Use this svg, simply found here: https://www.bfmtv.com/assets/images/BFMTV.svg

**histoire.default.png**
We already have that logo, it's called `histoiretv`.
You could replace it by this svg: https://static.wikia.nocookie.net/logopedia/images/8/80/Histoire_TV_%282019%29.svg/revision/latest?cb=20200314110416

**m6.default.png**
Please use svg! I found it within a second: https://commons.wikimedia.org/wiki/File:M6_1987_logo.svg

**m6music.default.png**
The logo you want to commit is of terrible quality.
Please use this svg: https://static.wikia.nocookie.net/logopedia/images/6/68/M6music-95cde0867d.svg/revision/latest?cb=20200412210630

**mtvhd.light.png**
The current one needs to be corrected indeed. But we already have a svg, please correct that one.

**mtvmusic24.default.png**
Please use the svg available on Logopedia: https://static.wikia.nocookie.net/logopedia/images/5/59/MTV_Music_24_%28Poland%29.svg/revision/latest?cb=20200724030851

**nrjhits.default.png**
Please use svg: https://upload.wikimedia.org/wikipedia/fr/3/36/NRJ_Hits_2017.svg

**tf1.default.png**
Please use svg: https://upload.wikimedia.org/wikipedia/fr/7/77/TF1_%282013%29.svg


Please edit and clean the svg's before commiting them.
If you're not up to the task I will help (because I don't want bad logos).
But if you can do it that saves me time!

**Comment by Hbt-Pierre** [comment]
Ok I will did that tommorow

**Comment by Hbt-Pierre** [comment]
I replaced all previous PNG icon to SVG.
Note that MTV MUSIC 24_ logo has a white background on the bottom instead of being transparent.

Moreover, I restored the original _MTVHD_ light icon, I am not up to perform this task.

**Comment by mrhotio** [comment]
Not sure about all the `Adobe Illustrator` svg's..... @Lexzie I'll let you decide if you wanna merge or not.

**Comment by Hbt-Pierre** [comment]
You talk about the comment in the file : 
`<!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->`

I can remove it if you want

**Comment by mrhotio** [comment]
No, removing the comment won't do...that indicates it's a adobe illustrator svg and in the past there have been compatibility issues when generating the picons.

**Comment by Lexzie** [comment]
I will look in to it later today.

I don't know about that compatibility issue.
I always use Inkscape and save them as optimized svg's, as is described here:
https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

**Review by Lexzie — APPROVED** [review]
Only `mtvhd.light.svg` is missing now.
I'll try to add it.

**Comment by Lexzie** [comment]
I forgot about the Abode Illustrator vs. Inkscape.
I don't know if the Adobe svg's will render the same? @hotio ?
I downloaded `histoiretv.default.svg` and saved is as an optimized svg, here's the difference:

afbeelding

@hotio I'll wait with the squash and merge until you approve the left one is okay?

**Comment by mrhotio** [comment]
We'll see what happens

**Comment by Lexzie** [comment]
Okay 👍🏻

**Pull request merged**
