### PR TITLE
Updates due to servicelist updates of kabeltex

### PR DESCRIPTION
**Pull request by r00tc0d3**

### CODE REVIEW

**Comment by Lexzie** [comment]
@r00tc0d3 could you share the lamedb file of KabelTex?

**Comment by r00tc0d3** [comment]
> @r00tc0d3 could you share the lamedb file of KabelTex?

Yes I could, but the lamedb does also contain services from satellites. Is that a problem?

**Comment by Lexzie** [comment]
No, no problem.

**Comment by r00tc0d3** [comment]
Herewith my lamedb file. The KabelTex list was scanned last weekend.

[lamedb.zip](https://github.com/picons/picons/files/4377086/lamedb.zip)

**Comment by Lexzie** [comment]
Thanks, I will use it for two other projects:
Rytec XMLTV EPG: https://forums.openpli.org/forum/52-en-rytec-xmltv-and-epg-support/
and my own cables.xml project:
https://www.sat4all.com/forums/topic/347544-cablesxml/
If there a changes for KabelTex you can contact me via that last one.

**Comment by r00tc0d3** [comment]
> Thanks, I will use it for two other projects:
> Rytec XMLTV EPG: https://forums.openpli.org/forum/52-en-rytec-xmltv-and-epg-support/
> and my own cables.xml project:
> https://www.sat4all.com/forums/topic/347544-cablesxml/
> If there a changes for KabelTex you can contact me via that last one.

Ok, thanks for the info. I will contact you if anything changes.

**Comment by Lexzie** [comment]
I've noticed a lot of service references of Kabeltex are not linked to a logo, do you use srp or snp picons and no picons missing? (Also on the radio channels?)

**Comment by r00tc0d3** [comment]
I altered the srp.index file. As far as I could find services in the index files I added a logo. My focus was not on the radio channels. A lot of serves are local TV stations and from the radio part most of them are stingray stations. I tried my best but I could not find more logos to add.
Maybe I am also doing something wrong. I just looked to the files and changed what was working for me.

**Comment by Lexzie** [comment]
And you don't have to do more if this is working for you.
If I have some spare-time I'll look into it some more.

**Pull request merged**
