### PR TITLE
5 new logos for Polish TV

### PR DESCRIPTION
**Pull request by BlazejosP**
I last few months was a many changes in Poland in case of frequencies and availability of TV station in Terrestrial TV. So here are new frequencies inside srp file some new names also inside snp and four NEW TV stations which started in last half a year.

### CODE REVIEW

**Comment by Lexzie** [comment]
[vidoctv.light.svg](https://github.com/picons/picons/pull/2300/commits/078aeab1df2338b5404c6a66b9f8f4337e6c6653#diff-2419178f520fcda42fe522b50c3385f516fc0cd11d93720a22e24ee96cf44e2c) has a background, please remove it.

Please correct srp.index and snp.index

**Review by Lexzie — CHANGES_REQUESTED** [review]
[vidoctv.light.svg](https://github.com/picons/picons/pull/2300/commits/078aeab1df2338b5404c6a66b9f8f4337e6c6653#diff-2419178f520fcda42fe522b50c3385f516fc0cd11d93720a22e24ee96cf44e2c) has a background, please remove it.

Please correct srp.index and snp.index

**Comment by AbuBaniaz** [comment]
Best not to submit changes from your master branch to this master branch. Instead,  create a new branch from your master branch. This is often called  a `feature branch`, for example `poland_changes_2024.07.18`, then submit a pull request from the new branch to this master branch

**Comment by Lexzie** [comment]
rmfm should probably be rmf

**Comment by AbuBaniaz** [comment]
Can you please also trim the empty space from the logos. It is called `resize page to selection` in Inkscape's `edit` menu.

**Comment by Lexzie** [comment]
> Can you please also trim the empty space from the logos. It is called `resize page to selection` in Inkscape's `edit` menu.

Still need to make some tutorials about these things.
But I'm afraid no-one will read it.

**Comment by BlazejosP** [comment]
Hello 
I will try improve that logos which are too big in canvas size. Also remove bacground from [vidoctv.light.svg](https://github.com/picons/picons/pull/2300/commits/078aeab1df2338b5404c6a66b9f8f4337e6c6653#diff-2419178f520fcda42fe522b50c3385f516fc0cd11d93720a22e24ee96cf44e2c)

**Comment by AbuBaniaz** [comment]
Added them here https://github.com/picons/picons/commit/6119502cf0e9309898cd4dda35ae17f5dac571af

I deleted the faulty light logo.

**Pull request closed without merging**
