### PR TITLE
Update some star logos.

### PR DESCRIPTION
**Pull request by TheLegoBatman**

### CODE REVIEW

**Comment by Lexzie** [comment]
Why the light logo not white?
afbeelding

**Comment by TheLegoBatman** [comment]
Why does it have to be white? If the default was black I agree that the light should be white. Since the default isn't black it looks better as a lighter version of the default.

**Comment by Lexzie** [comment]
It looks like white should be the default logo?
https://www.starchannel.nl/
https://www.starchannel.fi/
https://www.starchannel-bg.com/
https://www.starchannel.be/
https://www.starchannel-rs.com/
https://www.starchannel-hr.com/
https://www.starchannel-si.com/

**Comment by TheLegoBatman** [comment]
Logos on websites mean nothing since they are coloured to go with the dark theme. Default logos are supposed to go well with light stb themes. Default should never be white is my understanding.

**Pull request merged**
