### PR TITLE
[28.2E] Channel 4 HD light versions

### PR DESCRIPTION
**Pull request by BrianG61UK**
[28.2E] Channel 4 HD light versions

### CODE REVIEW

**Comment by BrianG61UK** [comment]
I just tested them and I'm not happy with the result so I'm closing this for now.

**Comment by Lexzie** [comment]
Why do you want to add a light logo?
The default logo is visible on a light and a dark background.

**Comment by BrianG61UK** [comment]
The "HD" and "+1" parts are invisible on dark backgrounds.

**Comment by Lexzie** [comment]
Sorry, on my mobile I couldn't see that the +1 and HD are grey.
If you're not able to do so, I can make the light logos if you want?

**Comment by BrianG61UK** [comment]
The "HD" and "+1" are a 50% transparent black at present.
I tried making them 50% transparent white, but the result was not good.
I was thinking I'd remove the transparency.
I could do it or you could. I'd be happy either way.

**Comment by Lexzie** [comment]
Or try f.e. 80% transparency.

**Comment by AbuBaniaz** [comment]
The broadcaster no longer have the HD text, might be better to remove the HD

**Comment by AbuBaniaz** [comment]
The `+1`  text  should be the same as `4`. Same applies to the `HD`  if we decide to keep it. At the moment, you cannot see them properly unless highlighted. Pictures to show issue

channel 4 hd

channel 4 hd 2

EDIT : these are light on transparent picons. Dark on transparent are invisible as per Brian's post

**Comment by BrianG61UK** [comment]
Okay. +1 same colour as main logo. No separate HD logo. I'll do them soon.

**Comment by AbuBaniaz** [comment]
I have done the links here:
https://github.com/picons/picons/pull/1620

**Comment by AbuBaniaz** [comment]
Logos here if it helps:
https://github.com/picons/picons/compare/master...AbuBaniaz:picons:channel4hd?expand=1

**Comment by BrianG61UK** [comment]
Since they're already in your branch, it's probably easiest if you do it. :-)
Thanks.

**Pull request closed without merging**
