### PR TITLE
Update snp.index

### PR DESCRIPTION
**Pull request by Dream1975**
ITV and FOLX

### CODE REVIEW

**Review by Dream1975 — COMMENTED** [review]
itv11londonplus1=itvplus1 (one 1 to much), but can't seem to change it myself after the pull request

**Comment by mrhotio** [comment]
push a new commit to the branch `patch-6`

**Review by mrhotio — CHANGES_REQUESTED** [review]
First fix the mentioned double `11`

**Comment by Dream1975** [comment]
"First fix the mentioned double 11" Done in patch-6

**Pull request merged**
