### PR TITLE
Arab 7W

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by medlakhdar** [comment]
Thank you very much to intérêt to arab 7w

**Comment by Lexzie** [comment]
> Thank you very much to intérêt to arab 7w 

You're welcome.

Unfortunately a lot logos can't be found. Sometimes I make them myself, but it's not possible with all of them.
Also searching for them would get better results if searching in Arab, which I can't.
If you can find (large) pictures of missing logos please send them in an issue here.

**Comment by medlakhdar** [comment]
I HAVE MAKE SOME ONES BUT YOU KNOW THAT CHANNELS ARE INSTABLE. I HAVE ALL NILESAT CHANNELS LOGO. HOW CAN I UPLOAD IT TO YOU

**Comment by Lexzie** [comment]
Just zip them and drag the zip-file in a reaction here.
Don't upload the actual picons with low resolution, but preferably svg-logos or png-logos with as high resolution as possible (not upscaled!).
I cannot receive all channels on 7/8W and 26E, so I you can and if you have an Enigma2 receiver, please make a recent scan and post the file /etc/enigma2/lamedb (in a zip-file) also in a comment.

**Comment by medlakhdar** [comment]
AL ASKARIYAH TV
Al Awhad TV KUWAIT
Al Maghribia MAROC
AL NAJAF AL ACHRAF IRAQ
Al Rafiden IRAQ
Alder3 Alro7ani LEBANON
Alkomail HD channel IRAQ
Alnajaf Alashraf IRAQ
ALWAQIE TV SAUDI
Asil TV KUWAIT
Aures TV ALGERIA
Dawacom TV UAE
Dohat Al-Quraan QATAR
ERE TV FRANCE
HEYA LEBANON
Kunouz TV LEBANON
Kunuz Altabia TV
palestine PALESTINE
Saout Alaqila IRAQ
The Kingdom Sat EGYPT
utv IRAQ
Waar TV hd IRAQ
Zarok TV  TURKEY
12 ARABIYA IRAQ
A1 LoveWorld Mena TV NIGERIA
Aghapy TV egypt
Al Basira EGYPT
Al Karma Family EGYPT
Almagd TV EGYPT
Almahaba tv EGYPT
ANOINTING TV CHANNEL ETHIOPIA
Arab Tourism JORDAN
BANNOUTA TV LEBANON
coptictv default
karameesh JORDAN
Libya Ahrar HD LIBYA
libya LIBYA
Mawda TV EGYPT
Al Awhad TV KUWAIT
Al Maghribia MAROC
AL NAJAF AL ACHRAF IRAQ
Al Rafiden IRAQ
Alder3 Alro7ani LEBANON
Alkomail HD channel IRAQ
Alnajaf Alashraf IRAQ
ALWAQIE TV SAUDI
Asil TV KUWAIT
Aures TV ALGERIA
Dawacom TV UAE
Dohat Al-Quraan QATAR
ERE TV FRANCE
HEYA LEBANON
Kunouz TV LEBANON
Kunuz Altabia TV
palestine PALESTINE
Saout Alaqila IRAQ
The Kingdom Sat EGYPT
utv IRAQ
Waar TV hd IRAQ
Zarok TV  TURKEY
a-a0ce-387eb954d452.png)
MBBC Alsrar IRAQ
Menhag Alnbowa EGYPT
Miracle Channel Egypt
naynawa allan IRAQ
Noor Alnada EGYPT
NOURSAT AL SHABAB LEBANON
noursat LIBANON
Qudaah JORDAN
story channel BERBERE
WTV Al Wasat TV LIBYA
Zee Zaman EGYPT

**Comment by medlakhdar** [comment]
THESE ARE CHANNELS TRANSPONDER 10727 H NILESAT AND TRANSPONDER 10777 H

**Comment by medlakhdar** [comment]
TRANPONDER 10873 H
Berbere Télévision FRANCE
DOLLY MOSALSALAT EGYPT
Elmoled EGYPT
Family Drama EGYPT
Libya Tantakheb LIBYA
Libya´s Channel LIBYA
PALESTINE TODAY PALESTINE
SAUDI 24 TV SAUDI
Top Movies TV EGYPT
TRT Kurdî TURKEY
Tunisia 1 HD TUNISIA
zilzal classic EGYPT
Al Jamahirya LIBYA
Al Quds Al Yawm PALESTINE
Al Rahma TV EGYPT
al sa3a MOSALSALAT EGYPT
al sa3a SHAROKHAN EGYPT
AL SA3AA MASRA7 EGYPT
Al Salam IRAQ
Al Tanasuh TV LIBYA
Al Yoom Zaman EGYPT
all tv EGYPT

**Comment by medlakhdar** [comment]
TRANSPONDER 10892 H
Afaq TV IRAQ
AL AHAD HD IRAQ
Al Ayam TV IRAQ
Al Nojaba TV IRAQ
Al Sharqiya News HD IRAQ
Alghadeer IRAQ
CINEMA PRO EGYPT
Dijlah TV IRAQ
M Classic EGYPT
Rudaw HD IRAQ
TokTok AFLAM EGYPT
TokTok Cima EGYPT

**Comment by Lexzie** [comment]
Could please submit the logos in a zip-file per transponder and name them with the station name?
I don't know all the logos.
You can find out the names on [Lyngsat](https://www.lyngsat.com/Nilesat-201-and-Eutelsat-7-West-A.html).

What I also notice is that all your logos are the same size, I guess that means you have scaled them?
I'd like to have the unscaled logos please.

**Comment by medlakhdar** [comment]
10727 h
zarok_tv_tr
Al Basaer
al_awhad_tv
al_malakoot_sat
al-haq
al-magharibia-uk
al-rafidain-tv-iq
an_najaf_al_ashraf_iq
asil-tv-ir
dawacom-tv
dohat-alquran-tv-qa
el_adjwaa_dz
ere-tv-fr
Kunuz Altabia TV
Libya Alghad
palestinian-satellite-channel-ps
saout-alaqila
utv-iq
waar_tv_iq
waqie-tv-sa

**Comment by medlakhdar** [comment]
10777 h
madrasetna-2

**Comment by Lexzie** [comment]
Please name the channels. I can't read Arab.

**Comment by medlakhdar** [comment]
10815 h
ctv_eg
dominique

**Comment by medlakhdar** [comment]
10815 h
aghapy_tv
al_basira_tv_eg
al_mahaba_tv
albasaer
alkarma-tv-family-us
almagd-tv-us
anointing-tv-channel-et
been-life
channel-12-arab-satellite
ctv_eg
dominique
libya-al-ahrar-tv-ly
libya-ly-ly
loveworld-arabic-ng
mawda
mbbc-tv-alsrar
Menhag Alnbowa EGYPT
miracle-channel-se
naynawa-allan
nour_el_shabeb_lb
nour_sat_lb
wasat-tv-ly

**Comment by medlakhdar** [comment]
10834 v
qatar_tv hd
qatar-tv-2-qa

**Comment by medlakhdar** [comment]
10853 h
4G CIMA EGYPT
4G CINEMA EGYPT
4G CLASSIC EGYPT
4G DRAMA EGYPT
alfath-atfal
al-maddah
al-moghtrb-al-yemeni
al-salam-quran
belody-aflam
BEYROUTH AFLAM EGYPT_
BEYROUTH AL YOUM EGYPT
BEYROUTH CINEMA EGYPT
BEYROUTH CLASSIC EGYPT
BEYROUTH DRAMA EGYPT
cima-tube
cinema-tube
cookies-kids
Drama 1 AL KHDIOUI 1 EGYPT
Drama 2 AL KHDIOUI 2 EGYPT_
Food Hub tv EGYPT
number-1
play-today
shoof-drama
sky-hkayat
tatt_7_tv
yallah-mosar3a

**Comment by Lexzie** [comment]
A lot of the logos you uploaded now are too small and/or have no transparent background.
If you have edited the logos removing the background and when you upscaled them in size you have I can use them, but what I didn't want was downscaled logos.

The big logos look nice, unfortunately I can't check them now, too low signal due too rain.

You also upload logos claiming to be on a particular frequency, but some are not.

**Pull request merged**
