### PR TITLE
Mauretania

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by mrhotio** [comment]
get your commits in order ....5 commits for 1 thing?? of which the most is old stuff

keep your master branch up2date, create a new branch from the master branch, do your modifications, push the new branch, create pr, merge, delete branch......

**Comment by Lexzie** [comment]
You said I didn't had to delete the branch but could keep working on my own branch.
Clearly I still don't understand it.
But as you also can see I deleted this branch, so next one will be a new branch and I will keep doing that for every commit.

**Comment by mrhotio** [comment]
I said that thinking you would know how to keep things tidy....😉

**Comment by Lexzie** [comment]
I hope it's going okay now?

**Comment by mrhotio** [comment]
Perfect 👍

**Pull request merged**
