### PR TITLE
Bbc rebrand

### PR DESCRIPTION
**Pull request by Varkentjes**
Whoops, wrong logo deleted

### CODE REVIEW

**Review by Lexzie — COMMENTED** [review]
I'm not convinced if a `HD` logo is needed at all.
On screen I did not see that BBC Scotland uses it, so imho we should use `bbcscotland` for both the SD and the HD channels.
@picons/piconcreators What's everyone's opinion?

**Comment by AbuBaniaz** [comment]
image

This is what I get on BBC Scotland HD

**Comment by Varkentjes** [comment]
I agree with Lexzie, but didn't want to remove any old logos beforehand. 

So we'd better get rid of all the obsolete HD logos from BBC then?

**Comment by Lexzie** [comment]
> So we'd better get rid of all the obsolete HD logos from BBC then?

Well whatever you come across, I'm not going to check them all.
Feel free to do so.

**Comment by Varkentjes** [comment]
OK. I will close this PR and create a new one to remove all unnecessary BBC HD logos

**Pull request closed without merging**
