### PR TITLE
Movistar rebranding

### PR DESCRIPTION
**Pull request by vpont**

### CODE REVIEW

**Comment by Lexzie** [comment]
Hmmm. I already made LaLiga 1-3.
Good thing I didn't start on the rest.

Great work, I'll check it later today.

**Review by Lexzie — APPROVED** [review]

**Review by Lexzie — APPROVED** [review]

**Review by Lexzie — APPROVED** [review]

**Review by Lexzie — CHANGES_REQUESTED** [review]
Can you make the LaLiga logos bigger just like the Campeones logos?

**Comment by Lexzie** [comment]
Great work.
If you like can you take a look at the Sky Sport and Sky Bundesliga logos (Germany), there are still a few not rebranded.

**Comment by Lexzie** [comment]
@vpont Can you make the Los Goya logo?
afbeelding
Replaces Cine Ñ

**Comment by vpont** [comment]
I'm not sure it's worth the time as it's just a temporary channel change for the "Los Goya" prizes.
It'll last until February 21th, then it'll go back to "M+ Cine Español".

**Pull request merged**
