### PR TITLE
That's TV Xmas

### PR DESCRIPTION
**Pull request by BrianG61UK**
That's TV Christmas logo for boxes that use snp.
srp boxes will have to just show normal That's TV Gold logo.

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
First cleanup the logo, there are still black pixels in the background (I know, it's a lot of work).

Ir we'll use this logo:
http://www.thats.tv/wp-content/themes/thatstv/img/thats-christmas.png

**Comment by BrianG61UK** [comment]
You prefer the cloudy shadows between the letters to be removed? Or is it the dark lines close to the gold letters?
Why would a white background be any easier to convert to transparent than a black one? If anything, I'd have thought the opposite would be true.

**Comment by BrianG61UK** [comment]
I'll try and get rid of most of the cloudy shadows around the letters.

**Comment by dalmore72** [comment]
That's TV Xmas

**Comment by BrianG61UK** [comment]
Thanks @dalmore72 that looks a lot better.

**Review by Lexzie — APPROVED** [review]

**Comment by BrianG61UK** [comment]
Thanks @Lexzie and @dalmore72

**Pull request merged**
