### PR TITLE
RTÉ, ITV & BBC additions

### PR DESCRIPTION
**Pull request by wedebe**
This update adds new service references for recent BBC, ITV and RTÉ changes on Astra 2 and Saorview

The following aren't included due to missing logos:
1DB3_82D_2_11A0000=atn
1DB9_82D_2_11A0000=ayozattv
2954_90B_3B_11A0000=bbcndra
2889_800_2_11A0000=bbcr4lw
669_7F0_2_11A0000=rb
1DB8_82D_2_11A0000=wordnetwork
1DBD_82D_2_11A0000=wrneurope

### CODE REVIEW

**Comment by TheLegoBatman** [comment]
Is this one correct  ```2904_90B_3B_11A0000=frees``` ?

**Comment by AbuBaniaz** [comment]
We don't have a logo called `rb`, so the the link being added is wrong.
The channel called `rb` is actually `sky intro channel` in hd.

**Comment by AbuBaniaz** [comment]
I also already added quite a few of the 28.2 ones you are adding again.  Please check what you are adding against what is on this repository instead of what you installed on your receiver.

May I suggest you remove your 28.2 services your remote and then scan again. There is no mechanism to clear unlisted transponders during enigma2 scans.

**Comment by Lexzie** [comment]
A lot of these "additions" are already in srp.index
These were not found:
```
DBA_82D_2_11A0000=92news
8C7_3EA_2174_EEEE0000=rte2xm
8CA_3EA_2174_EEEE0000=rtechill
4D3_3E9_2174_EEEE0000=rtechill
8C9_3EA_2174_EEEE0000=rtegold
8C6_3EA_2174_EEEE0000=rtepulse
8C5_3EA_2174_EEEE0000=rteradio1extra
2880_800_2_11A0000=bbcradiofoyle
287F_800_2_11A0000=bbcradioulster
849_3EA_2174_EEEE0000=saorview
```
But we have no logo named `92news`, I guess you mean `92newsuk`?
There is no logo named `bbcradioulster`.
Same for `saorview`.

Also:
```
1DB3_82D_2_11A0000=atn
1DB8_82D_2_11A0000=thewordnetwork
```
Already exists.

I don't know what `bbcndra` should be?

I'm guessing that with `bbcr4lw` you mean BBC Radio 4 LW (Longwave)?
So it's just BBC Radio 4.

There is no logo named `wrneurope`, is `worldradionetwork` the same?

So you're srp links should be:
```
1DB9_82D_2_11A0000=ayozat
2889_800_2_11A0000=bbcradio4
669_7F0_2_11A0000=bbcredbutton
1DBD_82D_2_11A0000=worldradionetwork
```

**Comment by AbuBaniaz** [comment]
@lexzie, I added the ayozat, 92newsuk, radio4 xtra links already and pretty sure the word radio network on too 

The `=redbutton` link you suggest is wrong, it should be `=sky`

@wedebe 
Please amend your pull request after a service scan. Only add what does not exist on this repository already.

**Comment by Lexzie** [comment]
@AbuBaniaz I just updated my local copy of the repository and deleted a few links that are indeed already added by editing my previous post.
Still some links missing?
I have not done a new service scan, no time anymore now. i just wanted to prevent double additions and help out what the right logonames probably are.


Furthermore, i don't know how to edit another one's PR.

**Comment by AbuBaniaz** [comment]
Apologies, the rescan comment was for wedebe.yes, a couple of missing entries, but most of what is being added in this pull request exists already.

We can only edit prs if the submitter ticks the option.

**Comment by AbuBaniaz** [comment]
I am closing this. I have added the Saorview ones from this pull request, one was a duplicate.  I did a scan of 28.2 and added the  missing ones I found.

**Comment by wedebe** [comment]
My apologies, I'd scripted and made further changes to the index manually... but forgot to clear stale data first.

**Comment by AbuBaniaz** [comment]
I have added this to keep the projects I have forked synced.
https://github.com/wei/pull#readme

Secondly, most of us check for duplicate entries and delete expired/wrong links them when adding/making changes. You could have seen the existence of the duplication then.

I added the 28.2 links 2 weeks ago
https://github.com/picons/picons/commit/c2ab00c6db06ffc83aa29d0c1d3b45e2c7e29b13

**Pull request closed without merging**
