### PR TITLE
VTM Gold

### PR DESCRIPTION
**Pull request by Varkentjes**
Station name will be changed on March 1, 2021

Source: https://vtm.be/caz-2-wordt-vtm-gold-en-brengt-elke-dag-de-grootste-vtm-klassiekers

### CODE REVIEW

**Comment by Lexzie** [comment]
When I added VTM 2, 3 and 4 there were SVG's.
I have to look if there's one for VTM Gold too.

**Comment by Lexzie** [comment]
On the website it's still Caz 2, so let's wait until March 1st.

**Comment by Lexzie** [comment]
I also came across this logo, so we have to know for sure which one will be used. (don't mind the black background)
afbeelding

**Review by Lexzie — COMMENTED** [review]
Let me try to find a SVG for this.

**Comment by Varkentjes** [comment]
I found a screenshot suggesting the new logo will be white/gold. But let's wait a few days to see what it will be in the end. Through this PR we are informed that there will be a change at Caz 2 soon. 

onsGeluk03-VTM-Gold

**Comment by Lexzie** [comment]
On the TV there's still Joe, on vtm.be there's still CAZ 2, but on the website op dpg Media there's the gold logo: https://www.dpgmedia.be/nl/merken/vtm-gold
Could we agree to use this one?
On the website where I found the other SVG's (https://www.advertising.dpgmedia.be/nl/merken/medium/televisie-9) still CAZ 2.

I'm considdering to change the other VTM logos too, so we'd only use the coloured ones (which are now the dark logos). Not the white ones.

**Comment by Varkentjes** [comment]
The new logo is currently visible on TV, but completely white. I suspect that, just as with NPO, RTL and SBS, the logo starts with color at the beginning of each program and changes to white after a few minutes. My preference is for a logo in full color (so gold)

**Comment by michaelarnauts** [comment]
@Varkentjes You might want to use this logo, since it's more square and better fits in with the other VTM logo's.

from: `https://images0.persgroep.net/rcs/PeXax8M8rTwNzkuZYa3Qh4ruLjA/diocontent/200304025/_fitwidth/500?appId=da11c75db9b73ea0f41f0cd0da631c71`

**Comment by Lexzie** [comment]
It looks like it's better indeed. Changed in PR #519 
By the way DPG Media still things the station is called Caz 2, so no SVG yet.

**Pull request merged**
