### PR TITLE
Updates Astra 2

### PR DESCRIPTION
**Pull request by Varkentjes**
Several updates Astra 2

### CODE REVIEW

**Review by Lexzie — APPROVED** [review]

**Comment by AbuBaniaz** [comment]
I don't seem to find the wionhd. What frequency is that on please?

**Comment by Lexzie** [comment]
> I don't seem to find the wionhd. What frequency is that on please?

I should be able to calculate that from the service reference...
Wait a moment.

**Comment by Varkentjes** [comment]
Knipsel

**Comment by Lexzie** [comment]
Yes, I calculated that transponder too:
D813_838_2_11A0000 =
SID = D813 = 55315
TID = 838 = 2104
ONID = 2

But SID 55315 is TJC (The Jewellery Channel)
afbeelding
afbeelding

**Comment by AbuBaniaz** [comment]
This is what I get.

```https://www.bizasialive.com/zee-set-to-launch-english-news-channel-wion-hd-in-uk-this-month/```

It is on 11264 V. Shows up as 52119
CB97_83C_2_11A0000

1_0_19_CB97_83C_2_11A0000_0_0_0_20210303192824

**Comment by Lexzie** [comment]
So King of Sat made a boo-boo. Who is going to adjust the links?

**Comment by Lexzie** [comment]
This is real cooperation, thanks guys!

**Comment by AbuBaniaz** [comment]
I also edited it.

Thanks @Varkentjes

**Pull request merged**
