### PR TITLE
Add some srp references for tele2 comhem

### PR DESCRIPTION
**Pull request by AbuBaniaz**
Add some srp index enties for tele2 comhem

### CODE REVIEW

**Comment by Lexzie** [comment]
Use `kanal5-cricroclot` in stead of `kanal5hd-cricroclot` as they no longer use a 'HD' logo.

**Comment by AbuBaniaz** [comment]
I have a referencing file made from the snp.idnex and it has not been updated. Hence the error..
I don't know which is the correct logo. kanal5 or kanal5-cricolot.

**Comment by Lexzie** [comment]
Like I said `kanal5-cricolot` is the right logo.
https://www.lyngsat.com/tvchannels/se/Kanal-5.html
https://logos.fandom.com/wiki/Kanal_5_(Sweden)
[Tele 2 Comhem](https://www.tele2.se/varfor-tele2/tele2-och-com-hem) is a Swedish provider.

`kanal5` is the logo for Kanal 5 (North Macedonia)
https://www.lyngsat.com/tvchannels/mk/Kanal-5.html
https://logos.fandom.com/wiki/Kanal_5_(North_Macedonia)

**Review by Lexzie — CHANGES_REQUESTED** [review]
Please change
`440_1F_A027_FFFF0000=kanal5`
to
`440_1F_A027_FFFF0000=kanal5-cricroclot`

**Comment by AbuBaniaz** [comment]
Ok, will do. What about kanal9?

**Comment by Lexzie** [comment]
> Ok, will do. What about kanal9?

That one is correct.
https://www.lyngsat.com/tvchannels/se/Kanal-9.html
https://logos.fandom.com/wiki/Kanal_9

**Comment by Lexzie** [comment]
You can check the channels Tele 2 Comhem carries here:
https://www.tele2.se/kundservice/tv-och-play/kanalplatser

**Comment by AbuBaniaz** [comment]
Here is his lamedb file, there were a few channels I could not see logos.

[lamedb (1).zip](https://github.com/picons/picons/files/14643392/lamedb.1.zip)

**Comment by Lexzie** [comment]
I will have a look later at the lamedb... (time to sleep now).
Found some logos already, I will make a new PR.
There are more wrong links I think.
Could you check these what the correct logos are?

I think `tv2-wapadedrud` should be `tv2-pistohicra`:
tv2-pistohicra is the Danish one, tv2-wapadedrud is Hungarian.

`tv3-pephawrego` should be either `tv3norge`, `tv3-pistohicra` (Danmark) or perhaps `tv3-cricroclot` (Sweden)?
tv3-pephawrego is the (obsolete) logo for TV3 (Ireland) which is renamed to Virgin Media One.
https://logos.fandom.com/wiki/Virgin_Media_One

I think `tv4-lichoridas` and `tv6-lichoridas` (Poland) should be `tv4` and `tv6-cricroclot` (Sweden)?
And maybe `algerie6` is also one of the Scandinavian TV6 channels? F.e. `tv6norge`?

`tv8` is Italian, `tv8-cricroclot` is Swedish.

**Comment by AbuBaniaz** [comment]
I have corrected some of them. Thanks.

We should delete any obsolete logos at some stage. Including the temporary links. Packages become too large. Eg valentine, james bond, etc

**Comment by Lexzie** [comment]
Sure, I will have the time when I'm retired... LOL

But you have a point.
You mean the ipk packages?
All not used logos if they are not linked in srp./snp.index they won't be in the ipk I think?
(I always try to delete unused links).

And if you delete a logo (which maybe took a lot time to build) and will be used again?
Or can we think of a way to move the logos to an archive?

**Pull request merged**
