### PR TITLE
ClipMyHorse.TV

### PR DESCRIPTION
**Pull request by Varkentjes**

### CODE REVIEW

**Review by Lexzie — APPROVED** [review]
The on-screen logo for ClipMyHorse.TV is just the logo (head of the horse in the circle).
Let's see how this works out as a picon.

**Comment by Varkentjes** [comment]
If you want I can also make a logo without text

**Comment by Varkentjes** [comment]
[clipmyhorsetv.default.option.zip](https://github.com/picons/picons/files/6250057/clipmyhorsetv.default.option.zip)

**Comment by Lexzie** [comment]
Of course, I could have done it too.
But first let's see if this is good visible.
I don't think it has to be the same as on screen, but sometime it's better f.e. when the logo is too wide.

**Pull request merged**
