### PR TITLE
MTV 00s SRP update

### PR DESCRIPTION
**Pull request by Varkentjes**
Two streams I could check have changed. There may be more, but I can't verify them. 

VH1 HD (Italy) is still transmitting

### CODE REVIEW

**Comment by Lexzie** [comment]
Can't change the srp.index in this Pull Request. Maybe because it's closed?

**Comment by Varkentjes** [comment]
I haven't closed anything so I have no clue

btw, after updating my picons, VH1 logo still showing on MTV 00s?

**Comment by AbuBaniaz** [comment]
I merged the pull request already.

Please check repo if more work is needed. If it is say what it is, and separately, say what it needs to be. So that there is distinction between bad/good, wrong/right

Thanks.

**Comment by Lexzie** [comment]
Working on a total update for VH1 > MTV in srp.index. There are some orphans which I want to cleanup too.
I thought it was easy to use this PR for that, otherwise I would make an own PR.

> btw, after updating my picons, VH1 logo still showing on MTV 00s?

What exactly do you mean? Do you use srp or snp and which sat/frequency/provider do you mean?
Have you done a rescan of the transponder? Some have changed to MTV 00's but not changed the channelname.

**Comment by Lexzie** [comment]
Looks like what I though was easy to do ended up in changing the srp.index on Varkentjes fork.
Closed it and will make an own PR (#751).

**Comment by Varkentjes** [comment]
I don't think it's possible that you can edit someone else's fork 

> What exactly do you mean? Do you use srp or snp and which sat/frequency/provider do you mean?
Have you done a rescan of the transponder? Some have changed to MTV 00's but not changed the channelname.

Nevermind, my settings file got corrupted. Everything is fine now.

**Comment by Lexzie** [comment]
Good to hear all is okay now.
Thanks again for your work.

**Pull request merged**
