### PR TITLE
srp mappings for vodafone cable

### PR DESCRIPTION
**Pull request by Mynacol**
(First contribution, bear with me)

Mostly mappings in `srp.index` (I just added them at the bottom of the file).
Some new picons for new channels. I am not good at vectorizing bitmap images, so two new PNGs. Both may be vectorized by someone else.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
I think that two of the logos you supplied are light versions. Are you sure you want those committed?
build-source/logos/antennesaar.default.svg
build-source/logos/sport1.default.svg

**Comment by Mynacol** [comment]
Thanks for the input. I dig some more and found more color variants.
Is it fine to have no `.default.svg` variant? The sport1 one has a dark and light variant, the [homepage](https://www.sport1.de/) uses the light one. So I am not sure which should be the default one.

And I vectorized the two PNGs \o/

**Review by Lexzie — CHANGES_REQUESTED** [review]
First of all thank you for adding the missing logos and links.
Unfortunately there's still a lot missing.
`80s80s` rescaled and added a light version.
`antennesaar` cropped, rescaled, coloured and added a dark version.
`beats` cropped, resized, renamed because there is no mention of radio in the logo and made a light version.
`cosmode` cropped and added a light version.
`energynrj` replaced with svg and added a light version.
`radio7` there's no mention of it being an exclusive German logo, so removed the `de` and added a random 10-character name. Replaced it with a logo with transparent background.
`sport1` this logo already exists under the name `sport1-wispelutri`.
And I saved them all as optimized svg's.
Please replace the logos with and add the extra logos which are in this zip-file:
[Vodafone.zip](https://github.com/picons/picons/files/7832474/Vodafone.zip)

Delete the logos `radio7de.default.png`, `sport1.default.svg`, `beatsradio` and the `energynrj.default.png`.

For the changes in srp.index I made them for you.
Put changes not at the bottom but in the top of srp.index, also it is common to sort them on the names of the logos.

**Comment by Mynacol** [comment]
Hey @Lexzie, thanks for the in-depth look. I for sure missed some details.

So in summary new picons for:
- 80s80s
-  antennesaar
- beats
- donau3fm
- energynrj
- radio7
- unserding

I deleted some again:
- cosmode: Instead using wdrcosmo
- sport1: already existing

At last, I rescaled all new SVGs to 800px and optimized them with scour (inkscape).
All are cropped and have a transparent background.

So I feel quite confident now. With your help we have mostly a default and light color variant (except for radio7 and unserding, which should look good on light and dark backgrounds).

Maybe you could check the `radio7` SVG? I poor-man vectorized it with [vectorizer.io](https://vectorizer.io/). The circle is not a real circle, for example.

Now I wait for the rebuild to check my changes...

---
And maybe we could add some more text to CONTRIBUTING.md, explaining to crop, delete/transparent background, scale to 800px and optimize svg?
The last step may be automated with Github actions (although I know you have bad experience with rendering errors; at least nowadays there is `--renderer-workaround` in scour's options, wich explicitly references librsvg)

If you want I could look into automating the SVG optimization stuff.

**Review by Lexzie — CHANGES_REQUESTED** [review]
The dark version of `antennesaar` is not needed, please delete.
There's still black in `cosmode.light.svg`. (my bad)
`radio7-wispelutri.default.svg` if you zoom in you see it is not okay.
F.e. the O and D are not perfectly round, the yellow circle is not good, like you said, the A not straight.
Unless you want to correct that (could be a lot of work) you can submit a better svg, otherwise no problem to use the png, it's resolution is big enough.

No need to delete `wdrcosmo` unless it will absolutely never be used again. And make sure there are no links to that logo anymore!

More text in CONTRIBUTING.md could be a good thing.
That is not totally up to me. I just add logos and links.
Same for automated Github actions. I have no knowledge how that works and you'll have to ask @mrhotio

**Comment by Mynacol** [comment]
I just deleted `antennesaar.dark.svg` and reverted `radio7` back to png.

With wdrcosmo/cosmode it's exactly the other way around. I deleted cosmode, which I previously added. I changed the one reference for cosmode (I checked `srp.index` and `snp.index` for references) to wdrcosmo (previously there).

**Comment by AbuBaniaz** [comment]
> Is it fine to have no `.default.svg` variant?

To me, it is look on infobar, channel list, Grid EPG  that is more important than what the broadcaster  has on their website.

More info here:
https://github.com/picons/picons/blob/master/CONTRIBUTING.md

**Comment by Lexzie** [comment]
There must always be a default logo.
If that logo is not good visible on a dark background, make a light version also.
Or if the logo is not good visible on a light background make a dark version.
Both a light and dark version for the same logo is theoretically not possible/wanted.

The white version is not mandatory and only done for some German (satellite) channels. I only add it if there was already a white logo for a particular channel and the logo changed.

**Comment by Lexzie** [comment]
> And maybe we could add some more text to CONTRIBUTING.md, explaining to crop, delete/transparent background, scale to 800px and optimize svg? The last step may be automated with Github actions (although I know you have bad experience with rendering errors; at least nowadays there is `--renderer-workaround` in scour's options, wich explicitly references librsvg)
> 

I checked the `CONTRIBUTING.md` and it's all in there:

crop logos:
_"No empty space around the logo."_

delete/transparent background:
_"Background should be transparent."_

scale to 800px:
This is optional and therefor no need to put that in the rules, I personally think it's usefull that SVG logos have this format and not ultra-tiny or superlarge.

optimize svg:
This can be found in the wiki: https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

**Comment by Lexzie** [comment]
> And maybe we could add some more text to CONTRIBUTING.md, explaining to crop, delete/transparent background, scale to 800px and optimize svg? The last step may be automated with Github actions (although I know you have bad experience with rendering errors; at least nowadays there is `--renderer-workaround` in scour's options, wich explicitly references librsvg)
> 

I checked the `CONTRIBUTING.md` and it's all in there:

crop logos:
_"No empty space around the logo."_

delete/transparent background:
_"Background should be transparent."_

scale to 800px:
This is optional and therefor no need to put that in the rules, I personally think it's usefull that SVG logos have this format.

optimize svg:
This can be found in the wiki: https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

**Comment by Mynacol** [comment]
Thanks for merging!

BTW: I plan to replace some outdated existing picons soon. And now I know the process ;)

**Pull request merged**
