### PR TITLE
Uktv rename

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by Lexzie** [comment]
I can't see the whitespace, I can't beleive I didn't crop the logos. Well I guess that can happen.
Anyhow, thanks for changing the srp-links.

**Comment by AbuBaniaz** [comment]
Sorry, bad choice of terms by me.  There was no whitespace, I just cropped the logos.

**Comment by Lexzie** [comment]
The on-screen logos are changed, but the names of the channels are not changed.
thumbnail_image001

Shall we link the (old) names to the new logos or do we wait if they will change the channelnames?
And what to do with the old logos?

**Comment by AbuBaniaz** [comment]
They have renamed now. We are missing a few that we can still add. 

I think we had better start a new topic about old logos

**Comment by Lexzie** [comment]
Are you able to make those +1 and the U&DaveJaVu logos?
If you like me to do it, that can take a while.
Maybe we'd wait a while and they will be available on Logopedia?

**Comment by AbuBaniaz** [comment]
I got the PNG files from Sky's website. I am useless at making logos.

**Comment by wedebe** [comment]
Alibi, Eden and Gold haven't been changed by UKTV: "U is UKTV’s free streaming service, providing instant access to shows from UKTV's free-to-air channels – U&Dave, U&DRAMA, U&W and U&YESTERDAY. "
https://corporate.uktv.co.uk/about-uktv/our-channels

Official svg files can also be found here :)
(but not, it seems in the same style as Sky boxes show)

**Comment by wedebe** [comment]
Here are the official logos (taken from u.co.uk tv guide pages) which I've filled with the official channel colours taken from the underline on each. (Sorry I don't have plus1 versions).

U Dave
U Drama
U W
U Yesterday

[U& Dave,Drama,W,Yesterday.zip](https://github.com/user-attachments/files/16257268/U.Dave.Drama.W.Yesterday.zip)

**Comment by Lexzie** [comment]
> Alibi, Eden and Gold haven't been changed by UKTV

Not yet, but we still have the current logos, haven't we?


> Here are the official logos (taken from u.co.uk tv guide pages) which I've filled with the official channel colours taken from the underline on each. (Sorry I don't have plus1 versions).

What's wrong with the logos we already have? They are the same.
https://github.com/picons/picons/blob/master/build-source/logos/uanddave.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/uanddrama.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/uandw.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/uandyesterday.default.svg

**Comment by Lexzie** [comment]
> I got the PNG files from Sky's website. I am useless at making logos.

Looks like the png logos are fine.

**Comment by wedebe** [comment]
> > Alibi, Eden and Gold haven't been changed by UKTV
> 
> Not yet, but we still have the current logos, haven't we?
> 
> > Here are the official logos (taken from u.co.uk tv guide pages) which I've filled with the official channel colours taken from the underline on each. (Sorry I don't have plus1 versions).
> 
> What's wrong with the logos we already have? They are the same.

official logos (taken from u.co.uk tv guide pages) with official channel colours taken directly from the official page in their original svg format.

Different transparency on `&` (which doesn't need separate light version) as well as zero horizontal padding and smaller file size (albeit at 3-4kb each)

**Comment by wedebe** [comment]
> > Alibi, Eden and Gold haven't been changed by UKTV
> 
> Not yet, but we still have the current logos, haven't we?
> 
> > Here are the official logos (taken from u.co.uk tv guide pages) which I've filled with the official channel colours taken from the underline on each. (Sorry I don't have plus1 versions).
> 
> What's wrong with the logos we already have? They are the same. 

[edited]
official logos (taken from u.co.uk tv guide pages) with official channel colours taken directly from the official page in their original svg format.

Different transparency on `&` as well as horizontal padding.

Screenshot 2024-07-16 at 23 43 00
Screenshot 2024-07-16 at 23 42 50
Screenshot 2024-07-16 at 23 42 30
Screenshot 2024-07-16 at 23 42 13

**Comment by Lexzie** [comment]
I got them from Logopedia.
@AbuBaniaz can you add the official logos?

**Comment by AbuBaniaz** [comment]
I am getting confused with the mulitple threads. I have downloaded them from logopedia and added them here, but I can't see the difference:
https://github.com/AbuBaniaz/picons/commit/ab1d9fb0aafdcf2d9bfaf18239b0b10c276dc757

**Comment by AbuBaniaz** [comment]
@wedebe 
I added your logos here: https://github.com/picons/picons/pull/2299/commits/84712544af22fcfb96fa6ed385a2ff8899de89a3

But it was a regression in my opinion, so I reverted them.  If you have better logos than what we currently have, please submit a pull request

**Pull request merged**
