### PR TITLE
Sunrise UPC Switzerland New

### PR DESCRIPTION
**Pull request by 4l3x2k**
Add new logos and link to service name and reference.

I could not find a suitable logo for blue stars. Everything else I (automatically) converted from bitmap to svg with Inkscape and stored as optimized svg with hints given in the picons wiki.

### CODE REVIEW

**Comment by 4l3x2k** [comment]
You wrote this to the commit in the branch. I forced pushed so the commit id and comment is not accessible anymore.

Lexzie wrote:
A lot logos don't meet our requirements, read the [contribution guideline](https://github.com/picons/picons/blob/master/CONTRIBUTING.md).

blue
Try to find better logos, like this one:
https://quickline.ch/media/3vippark/210322_bluetv_paket_sport.png
or make them yourself.
And provide light logos too.

freedom
This logo is a (temporary?) logo for UATV, so please also change all links linking to uatv (save the uatv logo, they might re-use it).
And please use this svg: https://uatv.ua/wp-content/uploads/2022/09/logo.svg
And provide a light logo too.

helvatiaone
This logo is too small and has no transparent background.
I did a Google search and found this within a few minutes:
https://images.zattic.com/logos/e6cd2b30f96851c74eda/black/original.svg

mysports10
A better logos is available on [Logopedia](https://logos.fandom.com/wiki/MySports_10).
Please try to find (or make) bigger logos for the rest too.
And provide light logos too.

startv
Again, [Logopedia](https://logos.fandom.com/wiki/Star_TV_(Switzerland)) is your friend.
and provide a light logo too.

Also: https://logos.fandom.com/wiki/TeleBielingue?file=TeleBielingue_Logo.svg
and provide a light logo too.

telesudostschweiz
There is already a logo sudostschweiz. Maybe needs to be updated.

telez
Provide a light logo too.

wetterdottv
Why not use svg on their own site?
https://wetter.tv/images/wetter-tv-logo.svg
And provide a dark logo too.

Submit the links (on top of the existing ones) in alphabetic order (of the logos).

**Review by Lexzie — CHANGES_REQUESTED** [review]
I'm sorry to say this because I know you are doing a great and big job.
But when you convert bitmap to SVG you have to do a lot work to correct all the imperfections.
F.e. just look at the O's, they are not round.

To help you:
  -Try to find what font is used (f.e. with [Fontsquirrel's font identifier](https://www.fontsquirrel.com/matcherator)) and install it, then the letters will be okay.
-If a PNG is large enough, don't bother to convert it to SVG, just use the PNG.

I would really want to help you, but I must watch out for taking up too much time.

**Comment by 4l3x2k** [comment]
Thank you.

Do you think the other logos are ok except the blue's ones?

**Comment by Lexzie** [comment]
> Thank you.
> 
> Do you think the other logos are ok except the blue's ones?

If they are not converted they will be okay I guess.
Besides what was said about cleaning the SVG's they cannot contain a base64 image and convert all shapes to path (Shift-Ctrl-C).
I have to check them all to tell you if they are okay.

**Comment by 4l3x2k** [comment]
The bitmap version of the blue logos are too small. Less than 200px. The best one is the one you found but blue sport is not a channel. The channel name is also behind blue text instead of beneath it.

I can look at the bluezoomd logo and check whether the O's are better and use them in the other blue logos. If they are also useless I would remove the blue logos completely.

**Comment by Lexzie** [comment]
Oh I realise now that if your svg's would have paths and base64 images they would not have passed the check.
So that should be fine.

**Comment by Lexzie** [comment]
It might be a lot of work, but you could build the blue logos.
Right now I don't have the time to do it. But I already found svg's for the logo of Blue:
https://tv.blue.ch/assets/images/static/logo-liveform.svg
And the letters `blue TV`:
https://tv.blue.ch/assets/images/static/logo-text.svg
So now you have to find which font the letters Sport, Zoom etc. are...

**Comment by 4l3x2k** [comment]
Did you thought I only imported the bitmaps into an svg? :-)

No! As I said they are converted by Inkscape with "redraw bitmap" and a algorithm that provided best results for me.

Therefor even text is a path (automagically) ;-).

I manually applied the color and gradients.

I'll try to find the font for blue logos.

**Comment by Lexzie** [comment]
> Did you thought I only imported the bitmaps into an svg? :-)
> 
No

> No! As I said they are converted by Inkscape with "redraw bitmap" and a algorithm that provided best results for me.
> 
Even so, you clearly see imperfections

> Therefor even text is a path (automagically) ;-).
> 
Of course, I already corrected the comment about path.

> I manually applied the color and gradients.
> 
Good work

> I'll try to find the font for blue logos.

I'm willing to help you when I have more time

**Comment by 4l3x2k** [comment]
Do you think that the Pull Request is OK if I would remove the blue channels?

**Comment by Lexzie** [comment]
> Do you think that the Pull Request is OK if I would remove the blue channels?

The MySports logos are not okay too.

**Comment by Lexzie** [comment]
I made the blue logos for you. I guess you could make the light logos from these?
[blue.zip](https://github.com/picons/picons/files/10367547/blue.zip)

When I have time again I will try the other logos.

**Comment by AbuBaniaz** [comment]
@4l3x2k 
Please delete the ones that are not acceptable. You can add those ( in an acceptable form)  on a different pull request later

@Lexzie 
Please add the acceptable logos from this request.  I have already added the blue ones

**Comment by Lexzie** [comment]
> @Lexzie Please add the acceptable logos from this request. I have already added the blue ones

@AbuBaniaz how do I do that? i am using GitHub Desktop.

**Comment by 4l3x2k** [comment]
Removed my sports logos and added light versions of the blue logos based on the new logos provided by @Lexzie .

**Comment by Lexzie** [comment]
Please remove the Tele D logo too, it is not okay.
Didn't I found a png? Can't find a big one anymore.

Found a svg, you only have to change the colors:
https://www.tele-d.ch/fav/safari-pinned-tab.svg

**Comment by 4l3x2k** [comment]
Done

**Comment by Lexzie** [comment]
> Done

Tele D logo is missing the orange parts.

And I see that the one I found on their website is crappy too.
The letters are not straight.
If you have not done it yet, please correct the logo.
Or use your one and correct that (f.e. the D is not correct).

**Comment by 4l3x2k** [comment]
This lasts until tomorrow. It's too late for me now.

Thank you for the support and patience.

**Comment by AbuBaniaz** [comment]
@Lexzie 
Please list the logos that are correct and I will add them. Otherwise, we will be here until 2024 with this request.

Pity the pull request doe not allow maintainer edits

**Comment by Lexzie** [comment]
@AbuBaniaz 
> @Lexzie Please list the logos that are correct and I will add them. Otherwise, we will be here until 2024 with this request.

The logos that are okay and can be added:
```
blueaction.light.svg
blueprime.light.svg
bluesport1.light.svg
bluesport2.light.svg
bluestars.light.svg
freedom.default.svg
freedom.light.svg
helveriaone.default.svg
rmcsportaccess1.default.svg
startv.default.svg
startv.light.svg
sunrise.default.svg
telebielinge.default.svg
telebielinge.light.svg
telez.default.svg
telez.light.svg
wetterdottv.default.svg
wetterdottv.light.svg
```
Line `teledhd=teled` must be deleted from
snp.index

Line `24A4_17_1_FFFF0000=teled`must be deleted from
srp.index


> Pity the pull request doe not allow maintainer edits

Yes that's what I meant by how do I do that?

**Comment by Lexzie** [comment]
@4l3x2k I have altready found out which fonts are used for the MySports logos, so I will make them and the PR.
After that you only have to add the entries for snp.index and srp.index.

I can also make the logo correctly for Tele D if you want?

**Comment by AbuBaniaz** [comment]
I have added the ones @Lexzie said were correct, apart from wetterdot. 

This is unnecessary/extra work on our part.

@4l3x2k 
Please update your pull request.

**Comment by Lexzie** [comment]
> I have added the ones @Lexzie said were correct, apart from wetterdot.

What's wrong with the `wetterdottv` logo?

**Comment by Jasmeet181** [comment]
I have MySports and TeleD logos in my German repository if you want to copy them.
https://github.com/Jasmeet181/mediaportal-de-logos

**Comment by 4l3x2k** [comment]
Never thought that adding some logos is that hard and long process :-).

TeleD is now colored.

**Comment by AbuBaniaz** [comment]
It normally is straight forward. There have been several issues with the logos you are submitting.

With regards to wetterdot, your default logo looks like a light one to me.

**Comment by AbuBaniaz** [comment]
Why are you deleting the last/blank line at the end of the srp file?

**Comment by 4l3x2k** [comment]
> It normally is straight forward. There have been several issues with the logos you are submitting.
> 
> With regards to wetterdot, your default logo looks like a light one to me.

Then the learning curve is very steep.

The standard logo of wetterdottv has white letters. So I don't know what standard should be?
Maybe the dark variant should become standard and the standard variant light?


> Why are you deleting the last/blank line at the end of the srp file?

I do not do that. It's just that currently there isn't a newline there and Github is complaining about it.
Therefore, if there is a newline at the end, the symbol disappears. So I added a newline.

**Comment by 4l3x2k** [comment]
I could also do some kind of frame around the wetterdottv logo.

**Comment by Lexzie** [comment]
> The standard logo of wetterdottv has white letters. So I don't know what standard should be? Maybe the dark variant should become standard and the standard variant light?

In my opinion:
When the standard logo on TV or website is light then you have to add the other as dark.
When the standard logo on TV or website is dark then you have to add the other as light.
Either way is also fine, as long as there is at least a default logo.


> I could also do some kind of frame around the wetterdottv logo.

Not if that's not what they normally use.
As far as I can see on the website they don't.

> I have MySports and TeleD logos in my German repository if you want to copy them. https://github.com/Jasmeet181/mediaportal-de-logos

So, I won;t bother making the logos and use those.

Here are they from Jasmeet181's repository renamed in our file format.
In my opinion there's no need for a light variant, this grey is perfectly visible on a dark background.

[mySports+TeleD.zip](https://github.com/picons/picons/files/10395633/mySports%2BTeleD.zip)

**Comment by AbuBaniaz** [comment]
Context is the issue. What looks good/default on website is not always the same as what is on the TV.

On our project, default is the logo used as standard to make the picons.  If people want to add light, white etc, that is their choice.

**Comment by AbuBaniaz** [comment]
You cannot have `startvhd=startv` because there is `startvhd=star-drispocupr`. Please use the SRP reference in the SNP file

**Comment by 4l3x2k** [comment]
I give up wetterdottv because I do not know what to do.

@AbuBaniaz 
> With regards to wetterdot, your default logo looks like a light one to me.

@4l3x2k 
> The standard logo of wetterdottv has white letters. So I don't know what standard should be?

@Lexzie 
> When the standard logo on TV or website is light then you have to add the other as dark.
> When the standard logo on TV or website is dark then you have to add the other as light.
> Either way is also fine, as long as there is at least a default logo.

@AbuBaniaz 
> Context is the issue. What looks good/default on website is not always the same as what is on the TV.
>
> On our project, default is the logo used as standard to make the picons. If people want to add light, white etc, that is their > choice.

So only starttv is left.

**Comment by AbuBaniaz** [comment]
The quotes in the comment make it hard to see what you are actually trying to convey.

We are all trying to add something to the community. So let's not fall out.

**Comment by 4l3x2k** [comment]
Thanks for merging after 3 weeks of discussions :-).

The logo https://wetter.tv/images/wetter-tv-logo.svg suggested by Lexzie has white font.
The statement was now that it looks like a light logo.
No problem, then this logo will be renamed to light. A dark variant with black writing is also no problem.
BUT
What is the standard variant with which the picons are built?

**Comment by AbuBaniaz** [comment]
> What is the standard variant with which the picons are built?

The one with 'default' suffix.

**Comment by 4l3x2k** [comment]
But there is no logo with suffix default.

The original from the website is renamed to light because of white font. The dark variant has black font.

The default is gray?

**Comment by 4l3x2k** [comment]
#1237 Should be fixed.

**Pull request merged**
