### PR TITLE
Tidy up DMAX, DMAX+1, Samaa TV

### PR DESCRIPTION
**Pull request by BrianG61UK**
Please DO tell me if I've messed something up.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
If the logo I added is no longer being used (you have deleted the reference to it), please delete it

**Comment by BrianG61UK** [comment]
> If the logo I added is no longer being used (you have deleted the reference to it), please delete it

Okay. Done!

**Comment by AbuBaniaz** [comment]
Can I ask why you are deleting the white version of the `dmaxhd` logo?


```
A default version of a logo should get the identifier .default at the end of the filename, additional types are possible, by using for example .light, .dark, .black or .white as an identifier.
```

**Comment by BrianG61UK** [comment]
> Can I ask why you are deleting the white version of the `dmaxhd` logo?
> 
> ```
> A default version of a logo should get the identifier .default at the end of the filename, additional types are possible, by using for example .light, .dark, .black or .white as an identifier.
> ```

**Comment by BrianG61UK** [comment]
> Can I ask why you are deleting the white version of the `dmaxhd` logo?
> 
> ```
> A default version of a logo should get the identifier .default at the end of the filename, additional types are possible, by using for example .light, .dark, .black or .white as an identifier.
> ```

Short answer: it looked wrong, not just a white version of the same logo.
Long answer to follow soon.
In the meantime, are you able to confirm for me that there is no DAX HD or DMAX+1 HD in the UK?

**Comment by BrianG61UK** [comment]
Long answer: there was no good reason.
I've replaced it.

**Comment by BrianG61UK** [comment]
@AbuBaniaz Thanks. Super quick too.

**Comment by Lexzie** [comment]
Is it a good idea to delete logos if it is not sure that they will be used again in the future?

Take good attention that you're not changing the hd-logos of the German, Turkish and/or Italian channels. They have a HD channel of DMAX.
So if there are links to those logos in either snp- or srp.index, don't delete them. In fact you can't because then you would get errors in the PR check.
In srp.index you can check if the service reference is still in use, if you know how that is is defined.

Also the channel might be in HD f.e. on cable.

**Comment by BrianG61UK** [comment]
DMAX+1 seem to now be using the "+1 DMAX" version I removed because I thought it was weird and probably from a non UK version of DMAX+1. If anyone wants to change it back, go ahead, otherwise at some point I'll probably have a go at working out how to do it. I see someone has already made the change for the srp icons, but not for the snp ones.

**Comment by AbuBaniaz** [comment]
I added it for 28.2 on the SNP file too.

**Comment by BrianG61UK** [comment]
Ah. I see now.
Though the light version is white rather than the same colour as the light one I made for DMAX (non +1).
I think I'll be able to submit a PR to make it match.

**Pull request merged**
