### PR TITLE
New icons for Great! channels (UK)

### PR DESCRIPTION
**Pull request by BrianG61UK**
New icons and index changes for Great! channels (previously Sony channels) (UK)
Second attempt.
I hope they're okay this time, especially srp.index, I hope I didn't change too many lines.
Thank you.

### CODE REVIEW

**Comment by mrhotio** [comment]
Why `greatclassplus1` as a name? It should be `greatclassicplus1`.

**Comment by mrhotio** [comment]
Besides that what do you think @AbuBaniaz ? Looks good to me after a rename...but been out of the game for a while.

**Comment by TheLegoBatman** [comment]
The +1 looks sort of pixelated. Can these be added instead.
[great_plus_one.zip](https://github.com/picons/picons/files/6576303/great_plus_one.zip)

**Comment by BrianG61UK** [comment]
> Why `greatclassplus1` as a name? It should be `greatclassicplus1`.

I choose the Sky name rather than the Freeview name. But obviously it makes no difference as long as all the links are present for both.

It just occurred to me, I didn't check what the Freesat names are!

**Comment by BrianG61UK** [comment]
> The +1 looks sort of pixelated. Can these be added instead.
> [great_plus_one.zip](https://github.com/picons/picons/files/6576303/great_plus_one.zip)

Yes, they do look a bit better.

**Comment by BrianG61UK** [comment]
Ask, if you want me to make the changes.

**Comment by mrhotio** [comment]
Read the guidelines please, we name the logos according the logo, not according to how one provider likes to name the channel. It clearly says 'classic' in the logo.

**Comment by mrhotio** [comment]
The issue has been brought up regarding the pixelation, so no need to ask if it should be fixed....just fix them.

**Comment by BrianG61UK** [comment]
> The issue has been brought up regarding the pixelation, so no need to ask if it should be fixed....just fix them.

Lack of antialiasing.

**Comment by BrianG61UK** [comment]
Closing for now. It got all messed up. I have to go for a walk to calm down.

**Comment by mrhotio** [comment]
😉no need to get worked up about it, despite our nitpicking still probably one of the best first time pull requests 👍

**Comment by BrianG61UK** [comment]
> :wink:no need to get worked up about it, despite our nitpicking still probably one of the best first time pull requests :+1:

Thanks.
I know it's mostly me. It's just the way I am. 

Opened again. But I'm still checking the index files. I may have copied old one(s) over the most recent ones.

**Comment by BrianG61UK** [comment]
Okay. I think I have it right now.

**Comment by mrhotio** [comment]
I still think it should be `greatmoviesaction` and `greatmoviesclassics` the `movies` is in those logos too....

**Comment by BrianG61UK** [comment]
> I still think it should be `greatmoviesaction` and `greatmoviesclassics` the `movies` is in those logos too....

Done. Except it says classic rather than classics in the logos so....

**Comment by mrhotio** [comment]
> Done. Except it says classic rather than classics in the logos so....

yep, typo on my part, :-)

**Comment by BrianG61UK** [comment]
Thanks!

**Pull request merged**
