### PR TITLE
Russia

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by Varkentjes** [comment]
Hi Lexzie, please take another look at `telekanal360.default` and `telekanal360.light`. Unfortunately the new logos now look exactly the same.

**Comment by Lexzie** [comment]
Weird. I corrected them twice.
No time now. Maybe tonight.

**Comment by Varkentjes** [comment]
I helped you a little bit, is this as it should be? 

telekanal360 default
telekanal360 light

**Comment by Lexzie** [comment]
Yes I think so.

**Pull request merged**
