### PR TITLE
Spain (2)

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by BrianG61UK** [comment]
@Lexzie Did you mean to include hidden control characters on line 3 of snp.index?
In this line:
325_65_22D4_EEEE0000=tv3catalunya

They're still present in the current snp.index and I'm wondering if they should be removed.

It's line 12919 in the, current as of me writing this, snp.index file.

**Comment by Lexzie** [comment]
I can't see any hidden control characters in Notepad++.
Feel free to delete them of course.

**Comment by Lexzie** [comment]
I didn't see anything with Visual Studio Code too.
But I think I deleted the characters, can you confirm that it is now okay?

**Comment by BrianG61UK** [comment]
Wow. I wasn't expecting such a quick response.
Yes looks normal now.
Thanks.

**Comment by Lexzie** [comment]
The email notification popped up, so I thought let's click it right away...
😄

**Pull request merged**
