### PR TITLE
ChartShowRetro Light Logo

### PR DESCRIPTION
**Pull request by BrianG61UK**
Add ChartShowRetro Light Logo.
(and compress dark one a bit)

### CODE REVIEW

**Comment by Lexzie** [comment]
You still have some work to do (that's why I didn't do it myself in the first place...):
afbeelding
See the red circled parts.

**Comment by BrianG61UK** [comment]
I think I'll wait and see if they ever actually start using this logo. If not maybe I'll change it to an SVG that attempts to match the on screen graphic. None of it shows much once it's shrunk down to 190x102 anyway.

**Comment by AbuBaniaz** [comment]
Imo, once merged, better commenting on commit instead of pull request.

There is a webp dark version that I got from logopedia attached to my initial commit, but it has an embedded image. Since the channel has officially launched, the logo could be on Sky website.

**Comment by AbuBaniaz** [comment]
The logo on sky's website is here
```
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb1224.png
```

**Comment by BrianG61UK** [comment]
Thanks!
I'm on it.
How did you find it? I can never find much on sky.com at all. Mostly, you can't do anything without an account. You can't really even get the info you need to decide if you want to get an account.

**Pull request merged**
