### PR TITLE
Remove ampersand from snp.index

### PR DESCRIPTION
**Pull request by BrianG61UK**
Remove ampersand from snp.index becasue it causes a weird message when building the picons packages.

### CODE REVIEW

**Comment by Lexzie** [comment]
Looks like I made that mistake. :(
Would you please not delete the line, but replace the `&` by `and`?
I can't do it right now.

**Comment by BrianG61UK** [comment]
As far as I can see, the correct line is already in the file.

**Comment by Lexzie** [comment]
In that case you indeed just had to delete the line.
Sorry, I couldn't check  right now.

**Comment by AbuBaniaz** [comment]
@Lexzie
It's definitely there.

**Pull request merged**
