### PR TITLE
Movistar+

### PR DESCRIPTION
**Pull request by Lexzie**
-Still need to find a better version of this logo:
afbeelding

-Have no new logo for La Resistencia por M+ yet.

-And don't know yet if the Deportes 1-7. La Liga 1-10 and Liga de Campiones 1-12 channels have their own logos, and then have to make those.

### CODE REVIEW

**Comment by vpont** [comment]
I can confirm M+ LaLiga 1-3 and M+ Liga de Campeones 1-2 have their own logos.

**Comment by vpont** [comment]
M+ Deportes 1-3 too, as you can see [here](https://www.movistarplus.es/programacion-tv)

**Comment by vpont** [comment]
saga
resistencia

**Comment by Lexzie** [comment]
The LaLiga and Deportes logos I probably can make.
The Sagas and La Resistencia 24H logos you found are a bit too small.

**Comment by Lexzie** [comment]
Already made the LaLiga 1-3 logos using the font `Apercu Movistar`.
Need more time for the rest.

**Comment by vpont** [comment]
I've [identified](https://www.fontsquirrel.com/matcherator?token=bfvmwceth9faiwjb) the font for "Sagas": **Integral CF (Bold)**
You can download it [from here](https://upfonts.com/integral-cf-font/)

**Pull request merged**
