### PR TITLE
TVV: Q2/Caz/Vitaya changed to VTM2 HD, VTM4, VTM3

### PR DESCRIPTION
**Pull request by WanWizard**
please double check if I've done this ok, it is my first PR here... :grin:

### CODE REVIEW

**Comment by Lexzie** [comment]
I have to close this without adding the logos, you should have removed the backgrounds (and make some dark variant logos).
It took me not more than a minute to find the right svg-logos on the website of vtm.
I will add them and all links.

**Comment by WanWizard** [comment]
Thanks, this isn't part of my skillset I'm afraid.

**Comment by Lexzie** [comment]
Thanks for the effort of course.
Funny that Caz 2 is not renamed.

**Comment by WanWizard** [comment]
I understand there are plans for Caz2, but not implemented yet.

I understand you need logo's in svg format (or png of no svg exist), and on a black background? Am I correct? Will try to do better next time... :smile:

**Comment by Lexzie** [comment]
> 
> 
> I understand there are plans for Caz2, but not implemented yet.
> 
> I understand you need logo's in svg format (or png of no svg exist), and on a black background? Am I correct? Will try to do better next time... 😄

There's a lot to consider, prefer SVG's above PNG's, but SVG's must be saved as optimized SVG and without base64 images in it and all object tranferred to path. PNG's should be of good quality, f.e. 800 pixels or more.
**No** background.
Crop the image so that no empty space is around the logo.
If logos are not good visible on a light background you also have to make and add a dark variant, if logos are not good visible on a dark background you also have to make and add a light variant.

Also read the [contributing guidelines](https://github.com/picons/picons/blob/master/CONTRIBUTING.md).
F.e. you made a link to `vtm2hd` while that logo wasn't committed by you (and did not exist already).

**Comment by WanWizard** [comment]
Clear, thanks. I'll do better next time!

**Pull request closed without merging**
