### PR TITLE
Local TV (UK)

### PR DESCRIPTION
**Pull request by BrianG61UK**

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
Have all these channels changed to just one?
I need to check later, right now they all show CBS Reality.
And you must have a default logo (which according to the website should be the dark one).
The light logo has dark edges around the letters, this one is better:
afbeelding

**Comment by BrianG61UK** [comment]
Yes, on satellite they have all been the same channel for some time with only one stream transmitted.
Now they have put them all under the same name "Local TV".
On Terrestrial I believe they are still separate channels.
If you can find better logo(s) with transparant background(s) go ahead and use them.

If you look you will see that I had already renamed the dark logo to default.

**Comment by Lexzie** [comment]
Sorry, I did not notice your second commit.
I found an even better logo (higher resolution), please use these, I don't know how to change your PR.

[localtv.zip](https://github.com/picons/picons/files/7533073/localtv.zip)

**Comment by Lexzie** [comment]
Thanks!

**Comment by BrianG61UK** [comment]
Thanks @Lexzie

**Pull request merged**
