### PR TITLE
trim logos

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by Lexzie** [comment]
What exactly did you do?
I can't see the difference (and I did trim them).
I just took the existed logos and added the +1 from another U& +1 logo.

**Comment by TheLegoBatman** [comment]
I think that it might look like  it's not trimmed if you look at it on github but it  is trimmed in fact.

**Comment by AbuBaniaz** [comment]
I have mentioned this to you before, but you don't agree. You can see the empty space on your commit. Here is a screen grab

Screenshot 2024-11-09 000222

All I did was resize page to selection in inkscape

**Comment by TheLegoBatman** [comment]
> I have mentioned this to you before, but you don't agree. You can see the empty space on your commit. Here is a screen grab
> 
> Screenshot 2024-11-09 000222
> 
> All I did was resize page to selection in inkscape

This is just on github website when in fact it is trimmed.

**Comment by AbuBaniaz** [comment]
If they were trimmed, why would inkscape trim them again? Please try it yourself.

Anyway, I'll close the request.

**Comment by TheLegoBatman** [comment]
I tried and it didn't trim anything. Maybe we are on different inkscape versions or maybe some bug in between then but it seems that there is no empty space looking at it in different editors.

**Comment by Lexzie** [comment]
Right now I have version 1.3.2, I see there is already version 1.4.
But like I said, the template was an existing (trimmed) logo from our repository.
And for me always the logos on the Github looked not trimmed while in fact they are.

**Comment by AbuBaniaz** [comment]
I was using version Inkscape 1.3.1 (91b66b0783, 2023-11-16), it trimmed the page.
I updated to Inkscape 1.4 (86a8ad7, 2024-10-11), it trimmed the page too.

To avoid confusions, I use:  `Edit > Resize page to selection`
`Shift + Ctrl + R`

If you are both happy there is nothing to do, that is fine with me.

**Pull request closed without merging**
