### PR TITLE
New icons and updated indexes for the Great! channels (previously Sony) (UK)

### PR DESCRIPTION
**Pull request by BrianG61UK**
I hope I've done it correctly. Don't hesitate to make corrections if necessary.

### CODE REVIEW

**Comment by mrhotio** [comment]
I'm not convinced on the logos...what's the point of the light versions? They don't look terribly to see by default....and why do a black and white +1 respectively?

**Comment by BrianG61UK** [comment]
> I'm not convinced on the logos...what's the point of the light versions? They don't look terribly to see by default....and why do a black and white +1 respectively?

Since I use light on transparent myself I thought the nearly black text wouldn't show well on dark backgrounds.

I wanted to avoid the problems like with the existing CBS Drama icon where the "CBS" is invisible on a dark background such as in the grid EPG.

But I won't be too upset if you wait for something better but please tell me what I did wrong.

**Comment by BrianG61UK** [comment]
Would you like me to resubmit with the +1 matching the color of the main text in the icon itself?

**Comment by BrianG61UK** [comment]
@mrhotio Would you like me to resubmit with the +1 matching the color of the main text in the icon itself?

**Comment by mrhotio** [comment]
imo yes please

**Comment by BrianG61UK** [comment]
Closing request. I will resubmit with improved icons. Also I will probably redo srp.index, it came out rather messy first time.

**Pull request closed without merging**
