### PR TITLE
RTL rebranding

### PR DESCRIPTION
**Pull request by TKOlit**
* new logos for RTL, RTLcrime, RTLliving and RTLpassion
* RTLplus -> RTLup

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
Can you make the Box Music Television logo 800px instead of this tiny picture?
Please leave the white letters in Radio Renascença logo.

**Review by Lexzie — CHANGES_REQUESTED** [review]
Please make white logos too for where there's already a white variant present.
Please make light logos for the ones with the dark text behind the logo, like RTL Crime, RTL HD etc.
I already made logos for RTL and RTL Up so you can see what I mean.
[rtl.zip](https://github.com/picons/picons/files/7231393/rtl.zip)

Don't forget the RTL UHD logo.

**Review by Lexzie — CHANGES_REQUESTED** [review]
No need to have these lines in snp.index anymore, please delete them.
```
2F30_441_1_C00000=rtlup
4E9C_E7_270F_FFFF0000=rtlup
D04F_2714_F001_FFFF0000=rtlup
```

**Review by Lexzie — APPROVED** [review]

**Review by Lexzie — CHANGES_REQUESTED** [review]
I just approved one commit. Should not apply to all.

**Comment by Lexzie** [comment]
Overall very much thanks for doing the work of course!

**Comment by Lexzie** [comment]
@picons/piconcreators 
Starting a discussion, should we go on with the horizontal logos or the stacked verions?
Especially the HD logos can get quite long.

Like this:
afbeelding
afbeelding

Instead of this:
afbeelding
afbeelding

**Comment by TKOlit** [comment]
> 
> 
> Can you make the Box Music Television logo 800px instead of this tiny picture?
> Please leave the white letters in Radio Renascença logo.

I don't know, why github lists all these older commits, but the only changes I actually have made, are the new logos for RTL.

**Comment by Lexzie** [comment]
Maybe that's because you're using the same branch and didn't delete the old one?

**Comment by Lexzie** [comment]
Please first clean this Pull Request.

**Comment by TKOlit** [comment]
> 
> 
> @picons/piconcreators
> Starting a discussion, should we go on with the horizontal logos or the stacked verions?
> Especially the HD logos can get quite long.
> ...
>
I personally don't like changing the layout of the logos in a way, which is definitly not intended by the designers of them.
But if you have an other opinion on that, feel free to change them.

**Comment by TKOlit** [comment]
> 
> 
> Please make white logos too for where there's already a white variant present.
> Please make light logos for the ones with the dark text behind the logo, like RTL Crime, RTL HD etc.
> I already made logos for RTL and RTL Up so you can see what I mean.
> [rtl.zip](https://github.com/picons/picons/files/7231393/rtl.zip)
> 
> Don't forget the RTL UHD logo.

Because of boredom, i have made light and white versions for all logos. ;)

**Comment by Lexzie** [comment]
> 
> 
> > @picons/piconcreators
> > Starting a discussion, should we go on with the horizontal logos or the stacked verions?
> > Especially the HD logos can get quite long.
> > ...
> 
> I personally don't like changing the layout of the logos in a way, which is definitly not intended by the designers of them.
> But if you have an other opinion on that, feel free to change them.

In the broadcasts RTL uses the stacked versions too, so they are designed as well.
I hoped to get more response on that quaestion. Maybe @mrhotio has an opinion about it.

**Review by Lexzie — COMMENTED** [review]
Nice

**Comment by Lexzie** [comment]
I still don't know if I can just merge this PR because of all of the old commits in it.
Maybe @mrhotio can confirm if merging is okay?

**Comment by TKOlit** [comment]
The list of changed files ( https://github.com/picons/picons/pull/848/files ) only contains the RTL logos, srp.index and snp.index.
So I would assume, that merging is ok.

**Review by Lexzie — APPROVED** [review]

**Comment by Lexzie** [comment]
You're right, so we'll see.

**Pull request merged**
