### PR TITLE
Added 3 Spanish DVB-T channels

### PR DESCRIPTION
**Pull request by tnijkes**
Added 3 Spanish DVB-T channels: La 1 HD, La 2 HD and DMAX.

### CODE REVIEW

**Comment by Lexzie** [comment]
If I look on the [website of the Spanish DMAX channel](https://dmax.marca.com/), I see a blue background, not green.
Is the blue background also seen in leaders etcetera on air?

**Comment by tnijkes** [comment]
I guess you're right.
I didn't notice the green on a black background. I thought it was blue...
On air, the logo has a white background.

Op zo 6 nov. 2022 om 13:00 schreef Alex ***@***.***>:

**Comment by tnijkes** [comment]
I committed 2 new logos (default and light version).
Original source from Wikipedia.

Op zo 6 nov. 2022 om 14:08 schreef Ton Nijkes ***@***.***>:

**Comment by Lexzie** [comment]
The name isn't conform our contribution guidelines, please change the filename, like described [here](https://github.com/picons/picons/blob/master/CONTRIBUTING.md#naming).
You could use _tramufrasw_, that's already in use for another Spanish channel.

_If the logo name you wish to use already exists, add a unique identifier like -trechuhipe, this is a pronounceable random 10 character string generated using this password generator. Grouping logos together using the same unique identifier is possible._

**Comment by tnijkes** [comment]
Thanks.
I renamed the files.

Op zo 6 nov. 2022 om 14:26 schreef Alex ***@***.***>:

**Comment by Lexzie** [comment]
You're doing a great job, but the one that uploaded that logo to Wikipedia deserves a slap in the face, look at the down-left corner of the D...
afbeelding
Left and right from the logo there is space left and above and below not the right colour.

Maybe I'm a perfectionist, but we want the logos to be as perfect as possible.

I took the liberty to make it right, would you please replace the logos with these ones?
**dmax-frulasicas default.svg**
dmax-frulasicas default

**dmax-frulasicas light.svg**
dmax-frulasicas light

And is the logo on screen like the light logo? So white background and transparent letters?

**Comment by tnijkes** [comment]
Thanks a lot. I replaced both.

The logo on screen indeed has fully transparent letters.
Even the white background has a little bit of transparency, but I don't
know if that's desired for a picon.

Op zo 6 nov. 2022 om 15:44 schreef Alex ***@***.***>:

**Comment by tnijkes** [comment]
You being a perfectionist, did you notice the difference between
paramountnetwork and paramountnetworkhd? ;-)
The latter lacks a light version.
Below are the light-on-black logos.

[image: paramountnetwork.png]
[image: paramountnetworkhd.png]

Op ma 7 nov. 2022 om 08:40 schreef Ton Nijkes ***@***.***>:

**Comment by Lexzie** [comment]
> 

The default logo of Paramount Network (HD) is also visible on a dark background, so why should there be a light version?

**Comment by tnijkes** [comment]
Thanks.
The blue on dark for Paramount HD  is barely visible.

Op di 8 nov. 2022 om 00:24 schreef Alex ***@***.***>:

**Pull request merged**
