### PR TITLE
Sky 70s SD

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Sky 28.2 has killed off some more  SD channels. As on a previous issue, we need to decide whether to have SD/HD picons. The broadcaster just uses one logo with no distinction.

**Comment by Lexzie** [comment]
When I look in the [Sky TV Guide](https://www.sky.com/tv-guide), the logos still have 'HD' in them.
I have no other way to check it.

My personal opinion: TV broadcasters should stop simulcasting HD and SD, saves a lot of bandwidth (= money) and don't use a HD logo.
But if they do use it on the screen and I can easily find or make one I will use it.

But I could not leave the SD channel with an HD-logo.
What I could have done delete the HD-logo and use the standard logo for both.

Done already a lot now today, if you can assure me that Sky doesn't use HD in their logos anymore, then we could change it all.
Oh, and if Sky UK does it, that doesn't mean Sky Deutschland and Sky Italy does that too.
So for each one we should check before we delete the HD-logos definately.

**Comment by Lexzie** [comment]
I you can receive Sky UK, can you supply a screenshot of the Sky Pride logo?

**Comment by AbuBaniaz** [comment]
> I you can receive Sky UK, can you supply a screenshot of the Sky Pride logo?

This is the logo they are using on the website. Sorry, I cant check the TV.
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb4016.png

**Comment by Lexzie** [comment]
Oh that’s easy to make.
I thought it might be more colourfull.

**Pull request merged**
