### PR TITLE
Revert star channel.

### PR DESCRIPTION
**Pull request by TheLegoBatman**

### CODE REVIEW

**Review by Lexzie — COMMENTED** [review]
Why do you insist on making a purple logo for the light variant?
There is no purple logo design for the Star logos.
Check the on-screen logos, check the website, Logopedia, Wikipedia, anything.
Nowhere a purple logo.

**Comment by Lexzie** [comment]
The default logo has the colour 241c32, the inversion of that is dbe3cd and that's a perfect colour for the light logo.
And that's not white.
Your purple logo does not resemble any of the logos I have seen on Star Channel.
Besides why also a dark logo while the default logo is fine on a light background?
We never have a dark **and** a light logo.

**Comment by TheLegoBatman** [comment]
That's the theme they are using for those logos. Dark purple is the colour theme that they are using since they started advertising the rebrand.  I'm sure if you google "star channel" and look at the images you'll see that it is the colour used. Logos should only be as light as they need, not nearly white as you seem to be doing for everything. Why are you "inverting" the colour? 

In regards to this dark logo seems I changed the name to dark since you made it.


Wikipedia: https://en.wikipedia.org/wiki/Star_Channel_(international)

Logopedia: https://logos.fandom.com/wiki/Star_Channel_(international)

Google: https://shorturl.at/lnoZ5

> Why do you insist on making a purple logo for the light variant? There is no purple logo design for the Star logos. Check the on-screen logos, check the website, Logopedia, Wikipedia, anything. Nowhere a purple logo.

**Comment by Lexzie** [comment]
On your Google link and on various sites of Star Channel itself I only see a (very) dark purple logo (colour 241c32, which is used for the default logo) or a white logo.
I invert the colour because that's what was told to do by @mrhotio and @AbuBaniaz 
Star TV (Disney) has clearly designed that light logo besides the dark logo, since they use it themselves.

I indeed did make that dark logo because I only had seen the white logo by then and assumed that was the default, so a dark had to be made. But if you replace the default logo which made the dark logo not necessary anymore, it should have been deleted from the repository. Sorry I thought you added the dark logo as well, I can't remember all what I have done.

But I probably have to rethink my understanding of a light (or dark variant) logo...

https://www.startv.pt/
This is the logo used on the website above: https://sire-assets-natgeo.fichub.com/assets/fox-star/images/StarChannel.svg?1712746001
https://www.facebook.com/StarLifePortugal
https://www.starchannel.fi/
https://www.starchannel.nl/
https://www.instagram.com/starchannelnl/

**Comment by TheLegoBatman** [comment]
As I wrote here https://github.com/picons/picons/pull/2038#issuecomment-1924658335 because a logo is a certain colour on a website doesn't mean that it's the colour of the logo.  

If indeed you were told to just invert colours I guess I misunderstood the gist of it all.

**Comment by AbuBaniaz** [comment]
If I said to invert colours, that was wrong by me or misunderstood. When we were copying/using the logos by jasmeet, he had dark/normal the opposite of what we do, so this may be what added to issue.

The purpose of the different types of logos are as described in the readme/contribution file.

I once again repeat, the colours we use should be based on what they appear like on receivers, it does not have to match the website or broadcast which sometimes are different because the broadcast ones are designed to show up on various backgrounds whereas the website are used on more controlled background colours.

**Comment by Lexzie** [comment]
Maybe there you have the cause of the different opinions.
I don't use a background (I use light on transparent picons).

But I'm all in for coloured logos, so I would not make a logo white (FFF) or black (000) when it is in colour.

Imho I just think the (almost) white logo looks better than the light purple one on a (mostly) dark background on the TV.

Just another option.

**Pull request merged**
