### PR TITLE
Update and cleanup Ukrainian 4W

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by Lexzie** [comment]
I don't know how to add the missing file.

**Comment by AbuBaniaz** [comment]
You have added links for which there is no logo. This is mentioned in the failure message. Delete those lines or correct them if it's a typo.

'uazakarpattya'

**Comment by Lexzie** [comment]
Yes, I know what's wrong, I forgot to add the logo. I can't add it anymore to this pull request?
If not, how do I delete that line?

**Comment by AbuBaniaz** [comment]
Add the commit to the branch from which you submitted the pull request

**Comment by AbuBaniaz** [comment]
On the web version, there are three dots in top right of files being amended. There is an edit option there.

**Comment by Lexzie** [comment]
I guess you already fixed it.
I had no time today. To bad, now I still don't know how I could have fixed it.

**Pull request merged**
