### PR TITLE
Update srp.index

### PR DESCRIPTION
**Pull request by Varkentjes**
* Sorted out about 1400 duplicate ServiceReferences and removed half of these. This is to avoid confusion and that wrong picons appear when someone modifies a previously used ServiceReference. And hopefully this will save a little bit of time in the build process. ;-)
* 1 typo detected in movistarlaliga4 

About 700 duplicates left to sort out. But these have different names so it takes me more time to check which one is correct.

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
Sorry, I started on top and see you delete references for Rai 3.
These are not duplicates!
There are a lot of Rai 3 versions and they all use the same logo.

The next example (`12C_9_85_C00000=eurosport360hd`) is indeed a duplicate, the same service reference is twice present in srp.index.

Please check all references you want to delete that they really aren't in use!
I have spent a lot of time adding those references (without the need for me, since I use snp-picons), so I will not be happy if you would delete them again!

**Comment by Varkentjes** [comment]
Hi Lexzie, I think you miss my point.

4550_30D4_13E_820000=rai3 appears twice in the list, line 23 and line 178 again
4555_30D4_13E_820000=rai3 appears twice in the list, line 28 and line 179 again
8_6_6_CE40000=somos on lines 7988 and 9512
6B_65_53_CE40000=rtpacores on lines 9128 and10030
12C_9_85_C00000=eurosport360hd on lines 833 and 834, etc.

What I did is sorted everything out and only took out the duplicates. I have checked everything carefully and assume a working list as the end result. 

Please take one more time to check a few random samples from the list, I also spent a lot of time cleaning up the list!

**Review by Lexzie — APPROVED** [review]

**Comment by Lexzie** [comment]
I'm sorry, you're correct. In dutch we say: I didn't look further than my nose length. (Probably a very very bad translation in English) 😆 

Until now I didn't check these doublures, what I did do was deleting the same reference if I added a new one.
I also created a Excel sheet to check whether a link exists in both srp.index and snp.index.
If you work with it like it is designed (needs some explanation), then it's very usefull to check a lot of references and names.
I have done that for 28.2/23.5/19.2/13E, for which I try to upload a fresh scan every month, but takes a lot of time and sometimes life get s in the way.

Working with that Excel sheet you have to be sure to work use the latest srp. and snp.index and check data which you get after a scan you just have done.
Also be aware that some links in snp.index are done with an srp-link because the name is the same as a channel with a different logo. So when you think (with that Excel file) that a link is incorrect, you also have to check whether the link is done with the service reference instead of the name.

**Comment by TheLegoBatman** [comment]
Also don't spend a lot of time doing this sort of processing manually, as it's not only not worth it, as it can be done in a second with one command.

**Pull request merged**
