### PR TITLE
Qmusic Thema

### PR DESCRIPTION
**Pull request by Varkentjes**

### CODE REVIEW

**Comment by Lexzie** [comment]
@Varkentjes could you make a logo for `Qmusic Nederlandstalig` or tell me what font is used or where you find the logos?

**Comment by Varkentjes** [comment]
Warsaw Gothic I used. It's not exactly the same, but it's the closest.

**Comment by Lexzie** [comment]
Would you like to do it please?

**Comment by Varkentjes** [comment]
Already working on it

**Comment by Lexzie** [comment]
Great!
This is the stream: `https://23843.live.streamtheworld.com/QMUSICNL_NEDERLANDSTALIGAAC_96.aac`

**Pull request merged**
