### PR TITLE
Vodafone Germany

### PR DESCRIPTION
**Pull request by 4l3x2k**
Changed servicerefs after TV frequency changeover. Old service refs
are kept until changeover is completed.

1+1 International
Old = D04D_2726_F001_FFFF0000
New = D04D_2725_F001_FFFF0000

Al Jazeera Int (eng)
D16E_2714_F001_FFFF0000
D16E_2715_F001_FFFF0000

Astro TV
D16C_2726_F001_FFFF0000
D16C_2721_F001_FFFF0000

Bibel TV
D09B_2714_F001_FFFF0000
D09B_2715_F001_FFFF0000

Boomerang
001C_0004_0085_FFFF0000
D09C_2713_F001_FFFF0000

CGTN
?
D118_2713_F001_FFFF0000=cgtn

CGTN Documentary
?
D0FE_2713_F001_FFFF0000=cgtndocumentary

CNBC Europe (eng)
D049_2726_F001_FFFF0000
D049_2725_F001_FFFF0000

Cartoon Network
C617_2718_F001_FFFF0000
C617_2713_F001_FFFF0000

Channel21
D10A_2715_F001_FFFF0000
D10A_2712_F001_FFFF0000

Curiosity Channel
D099_2713_F001_FFFF0000
D099_2715_F001_FFFF0000

DAZN 2
C3AA_2721_F001_FFFF0000
C3AA_2724_F001_FFFF0000

DAZN 2 (Sky)
C73A_2721_F001_FFFF0000
C73A_2724_F001_FFFF0000

DELUXE MUSIC
D04B_2726_F001_FFFF0000
D04B_2721_F001_FFFF0000

Das Erste HD
2B5C_041B_0001_FFFF0000
283D_041B_0001_FFFF0000

Deutsches Musik Fernsehen HD
C38F_2722_F001_FFFF0000
CBF2_2710_F001_FFFF0000

Duna TV (hun)
C75F_2726_F001_FFFF0000
C75F_2725_F001_FFFF0000

Fix & Foxi
C3CB_2713_F001_FFFF0000
C3CB_2715_F001_FFFF0000

HOME & GARDEN TV
C487_2717_F001_FFFF0000
C487_2713_F001_FFFF0000

HSE
D17E_2717_F001_FFFF0000
D17E_2713_F001_FFFF0000

HSE Trend
D116_2726_F001_FFFF0000
D116_2712_F001_FFFF0000

Halk TV / Kanal Avrupa (tur)
CFD3_2715_F001_FFFF0000
D055_2725_F001_FFFF0000

Hope TV
D117_2715_F001_FFFF0000
D117_2712_F001_FFFF0000

Juwelo TV
D173_2715_F001_FFFF0000
D173_2712_F001_FFFF0000

K-TV
?
D119_2713_F001_FFFF0000=ktv

MTV
CF0C_2714_F001_FFFF0000
CF0C_2715_F001_FFFF0000

NDR FS NDS HD
2859_044D_1_FFFF0000
2857_044D_1_FFFF0000

NHK WORLD-JAPAN (eng)
CF80_2714_F001_FFFF0000
CF80_2715_F001_FFFF0000

Nick.Jr.
CF0E_2717_F001_FFFF0000
CF0E_2713_F001_FFFF0000

Prime Video Sportsbar
155_3_85_FFFF0000
155_3_85_FFFF0000=primevideo

QVC
D170_2717_F001_FFFF0000
D170_2713_F001_FFFF0000

QVC Style
D115_2726_F001_FFFF0000
D115_2712_F001_FFFF0000

QVC2
C61A_2726_F001_FFFF0000
C61A_2721_F001_FFFF0000

RTL HD
C35C_271F_F001_FFFF0000
C35C_2723_F001_FFFF0000

RTLZWEI HD
C35B_271F_F001_FFFF0000
C35B_2727_F001_FFFF0000

SAT.1 HD
C362_271F_F001_FFFF0000
C362_2723_F001_FFFF0000

SONY AXN HD
C367_271F_F001_FFFF0000
C367_2722_F001_FFFF0000=sonyaxn

SPORT1+ HD
C355_271F_F001_FFFF0000
C355_2722_F001_FFFF0000

SR Fernsehen
6F46_041B_0001_FFFF0000
6EE2_041B_0001_FFFF0000

SR Fernsehen HD
C390_2722_F001_FFFF0000
288A_2722_F001_FFFF0000

Silverline
C481_2717_F001_FFFF0000
C481_2713_F001_FFFF0000

Sky Cinema Fun
201_1_85_FFFF0000
201_1_85_FFFF0000=skycinemafun

Visjon Norge (nor)
?
D036_2725_F001_FFFF0000=visjonnorge

Vodafone TV
C488_2717_F001_FFFF0000
C488_2713_F001_FFFF0000

WDR HD Köln
6EA5_041B_0001_FFFF0000
6EAC_041B_0001_FFFF0000

sonnenklar.TV
D16F_2714_F001_FFFF0000
D16F_2715_F001_FFFF0000

tagesschau24 HD
C38E_2722_F001_FFFF0000
2887_2722_F001_FFFF0000

### CODE REVIEW

**Review by Lexzie — APPROVED** [review]
Thanks!
Will you cleanup the old links?

**Comment by 4l3x2k** [comment]
I could do that but the changeover is going to be completed in July and I do not know if it harms anyone if I remove them now.

**Comment by Lexzie** [comment]
Yes, you have to do that after the changeover is compete.

**Comment by 4l3x2k** [comment]
That's why I added the old and new service refs in the commit message so they can be worked on removed later :-).

**Pull request merged**
