### PR TITLE
SRP index changes

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by SmoothMC** [comment]
thx for merge

**Comment by AbuBaniaz** [comment]
No problem. Once you resolve the misunderstandings with the svg files, submit a new pull request.
Remember
Do not touch make changes to your master branch. other than keeping it in syns with upstream
The changes you want to make should be in a separate branch that you delete after changes from it are merged. 

Failing that, just raise issues as before.

**Comment by SmoothMC** [comment]
ok maybe i make a new branches for the logos and pull them step by step...

**Comment by AbuBaniaz** [comment]
After you resolve the issues with them. Otherwise they will be rejected. I'm not good at graphics, so can't help. For example, using inkscape, I save as optimised SVG, on exiting it replaces it. 

The SVG files I upload are normally from Jasmeet181's repo or ready made ones.

**Pull request merged**
