### PR TITLE
Delete some suspect links

### PR DESCRIPTION
**Pull request by AbuBaniaz**
Namespace is composed of network id and orbital position. These seem wrong.

### CODE REVIEW

**Comment by Lexzie** [comment]
The references ending on 0 are restreams of T2-MI transponders and the Spanish Abertis stations.
But I agree that should be the namespace of that particular satellite.

Some are IPTV streams.

The others are missing a '0', so that are typos.

I personally don't use srp-picons, so I add them for others.

**Comment by AbuBaniaz** [comment]
By changing the ignore dvb namespace subnet to no, you should get the network ID too to avoid the clashes.

**Comment by Lexzie** [comment]
> By changing the ignore dvb namespace subnet to no, you should get the network ID too to avoid the clashes. 

I know, I use that on DVB-T in the Netherlands since different regional stations use the same PID's in different muxes. Depending on your location you often can receive more regional stations from neighbouring frequencies.
On satellite I don't use that, but even so, not always the namespace ends on 0000.

**Comment by AbuBaniaz** [comment]
The checks are not completing. I will re-submit later

**Pull request closed without merging**
