### PR TITLE
4music becomes E4 extra; boxhits becomes 4music

### PR DESCRIPTION
**Pull request by BrianG61UK**

### CODE REVIEW

**Comment by BrianG61UK** [comment]
4music becomes E4 extra; boxhits becomes 4music

**Comment by AbuBaniaz** [comment]
Brian, I don't think the  inferred transitions are correct across Terrestrial and cable. We could really remove the UK cable references too.

 I'll add the bare minimum changes in a separate commit and close this one. I hope that is OK

**Comment by BrianG61UK** [comment]
@AbuBaniaz Yes, thanks. I'm sure you know better than me what's the best thing to do.

**Comment by BrianG61UK** [comment]
@AbuBaniaz Oh wait. There's Freeview as well. 4Music is now called E4 Extra on Freeview as well. (for srp, snp will be okay as is)

**Comment by AbuBaniaz** [comment]
I have added it and also deleted box hits.  People in other Terrestrial areas can add to SRP file 

https://www.channel4.com/press/news/e4-brand-extension-sees-4music-become-e4-extra

**Comment by BrianG61UK** [comment]
Thanks.

**Pull request closed without merging**
