### PR TITLE
Logo and srp.index updates

### PR DESCRIPTION
**Pull request by SmoothMC**
Hey here is my first pull request

i add a few srp links (see the commits)
also add some new logo versions and Logo improvements
the Logo improvements are mostly file size optimisations 

# Logo Updates
* VOX up (png to svg)
* RTL (png to svg)
* Sat.1 (png to svg)
* rbb (Update to 2017 Version)
* mdr (Update to 2017 Version)
* Disney Channel HD (png to svg)
* welt (light Version update)

thats the biggest changes...more in the commits ;)

thx for merge

### CODE REVIEW

**Comment by mrhotio** [comment]
Please read the guidelines...

**Comment by SmoothMC** [comment]
Ok? where to find this guidelines for a pull request? what i'm doing wrong?

**Comment by SmoothMC** [comment]
A Answer would be nice. It take me a lot of time to add these changes, especially the work on the Logos. i don't want to loose these commits. Please

thx

**Comment by AbuBaniaz** [comment]
Don't delete the staging branch, the changes are in there.

 I'm sure @hotio will point out what you need to do differently when he gets a moment.

**Comment by mrhotio** [comment]
-disneychannel.default.svg didn't render in the preview, but appears to load in inkscape, probably because of the missing `<?xml version="1.0" encoding="UTF-8"?>`
-you are adding a disneychannel light version, while the default is prefectably readable on white and black backgrounds, same for the hd version
-disneychannel.whie.svg also didn't render in the preview
-you are modifying dmax.default.svg and it looks exactly the same
-you are modifying dmax.light.svg and it looks exactly the same
-you are modifying dmax.white.svg and it looks exactly the same
-you are modifying dmaxhd.default.svg and it looks exactly the same
-you are modifying dmaxhd.light.svg and it looks exactly the same
-you are modifying dmaxhd.white.svg and it looks exactly the same
-you are modifying healthtv.default.svg and it looks exactly the same
-you are modifying healthtv.light.svg and it looks exactly the same
-you are modifying healthtv.white.svg and it looks exactly the same
-mdr also didn't render in the preview
-and a bunch more of the same, modifying logos, just to modify them, because they look exactly the same

No offence, but that shit of "optimizing" svg files has to stop, in most cases it breaks compatibility with rsvg and the logo's are already in the repo, so you're not optimizing anything, you're just adding more bloat....Only required optimization is as seen on the wiki, and that has to happen before the logo goes in the first time.

PS: I have my doubts that running imageOptim on a bunch of files can be considered "a lot of time", I think other people have done a lot more work to get all the logos in as they are, I hate to see their hard work ruined by using imageOptim.

**Comment by SmoothMC** [comment]
ok i think this is a misunderstanding

i optimize that files because i deliver it to the picons repo by my self. (look in the issue section) most of them i create by my self and i edit them in adobe illustrator. But illustrator included many comments to the files and this increase the file size...so i optimize them like in the picons wiki
[Cleaning up SVG metadata](https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata). That is the reason the files look the same ;).

the reason why some logos didn't render anymore. i dont know. The building process run without any issue with these files. But i have to proof it. sry

edit: ok i proofe "mdr" and "disney channel" and in my browser and also the github desktop client they render without any issues. Mayby it is a bowser issue?

**Comment by AbuBaniaz** [comment]
I have cherry picked the SRP changes.

**Comment by mrhotio** [comment]
https://github.com/SmoothMC/picons/commits/a498fa0a97212f3e0c9417a44a295a459203028b/build-source/logos/dmax.default.svg

Is that clear enough? And if you followed the wiki, that illustrator crap wouldn't be in there....

**Comment by mrhotio** [comment]
@SmoothMC in hindsight you should have better explained your intentions....whenever I see words like 'optimize' or 'imageoptim', it's straight to the close pull request button....

**Comment by SmoothMC** [comment]
ok
i start from the beginning. i re-save all my svg's with inkscape (wiki like) after that i make e new branch and then a new pull request. in the new branch i will also include the logos that already delivered in my issues #94 #92 #91 #88 and #87 because they also need to be re-save with inkscape. hopefully this is ok.

how do you say...
You never stop learning...
i'm on it...sry for the confusion

**Pull request closed without merging**
