### PR TITLE
Add basque radio channels

### PR DESCRIPTION
**Pull request by jlazkano**

### CODE REVIEW

**Comment by Lexzie** [comment]
Why add the `etb4` logo while there is already a svg logo?

**Comment by Lexzie** [comment]
Replaced the png's with svg's in commit be16c820a55553574a0c8a144d4d47f9b5a18341

**Comment by AbuBaniaz** [comment]
I think this was caused by jlazkano using the master branch in his fork. He first added the PNG, I did not merge it, I added svg file. He then did another pull request which got merged and added the PNG.

I'll delete it next time I'm on PC.

**Comment by Lexzie** [comment]
Already done it and replaced the other png's for svg's, see my previous comment.

**Pull request merged**
