### PR TITLE
GB News (UK)

### PR DESCRIPTION
**Pull request by BrianG61UK**
What do you think?

IMPORTANT NOTE: I haven't done the changes to srp.index yet! I'm not sure how to get the right values.

### CODE REVIEW

**Comment by Lexzie** [comment]
Do you have an Enigma2 receiver?
Just check in the WebIF or Menu > Information > Service
Make sure to strip the prefix and suffix.
Example `1:0:1:9:1:2A:DE80000:0:0:0:` will be: `9_1_2A_DE80000`.

**Comment by mrhotio** [comment]
Is that an actual GB News HD logo or is that something you made up?

**Comment by Lexzie** [comment]
The first one I think (https://en.wikipedia.org/wiki/GB_News), but the channel is not launched yet.
Is there already a (test) transmission on Astra 2?

Edit: Oops, I see you just ask about the HD logo.

**Comment by TheLegoBatman** [comment]
There is no HD on the logo displayed on screen.

Edit: The hd channel is on ```1:0:19:D093:83E:2:11A0000:0:0:0``` .

**Comment by BrianG61UK** [comment]
> Is that an actual GB News HD logo or is that something you made up?

I made up the HD bit underneath.

The rest is from https://en.wikipedia.org/wiki/GB_News but with the pointless very gentle gradient fills that the build process didn't like replaced by flat fills.

**Comment by Lexzie** [comment]
In my opinion we don't want a HD logo if the station is not using one.
This is a screenshot from Astra 2:
afbeelding

You should also check your settings on your Enigma2 box, in my scan I have `D093_83E_2_11A0000`.

What's our opinion about the background of the logo?
If we leave it transparent the 'N' isn't that obvious.

**Comment by BrianG61UK** [comment]
And on Freeview?
My box (running OpenViX) definitely shows EEEE02A2
Should it be EEEE0000 ?

**Comment by Lexzie** [comment]
> 
> 
> And on Freeview?
> My box (running OpenViX) definitely shows EEEE02A2
> Should it be EEEE0000 ?

Imho yes it should be EEEE0000, unless you have 'Ignore DVB-T namespace sub network' switched off.
See at the bottom:
afbeelding

**Comment by BrianG61UK** [comment]
> > And on Freeview?
> > My box (running OpenViX) definitely shows EEEE02A2
> > Should it be EEEE0000 ?
> 
> Imho yes it should be EEEE0000, unless you have 'Ignore DVB-T namespace sub network' switched off.

Got it. I had them on for some reason. Switched them off now.

**Comment by Lexzie** [comment]
I already made the changes.
Also when adding a svg-image open it first in Inkscape and save it as an optimized SVG.
You can read about it here: https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

Unless anyone disagrees I guess this should be right.
And, of course, as always: **Thank you very much for your PR!**

**Comment by Lexzie** [comment]
> 
> 
> > > And on Freeview?
> > > My box (running OpenViX) definitely shows EEEE02A2
> > > Should it be EEEE0000 ?
> > 
> > 
> > Imho yes it should be EEEE0000, unless you have 'Ignore DVB-T namespace sub network' switched off.
> 
> Got it. I had them on for some reason. Switched them off now.

They should be switched ON. See my screenshot for DVB-S and DVB-C that's the correct setting.
For DVB-T I have it switched off, but that's because the nature of the Dutch DVB-T2 network.
They use the same SRP for all the regional stations, in this case I can receive multiple regional stations with the right logo and with the right EPG. Don't know if that is an issue for Freesat.

**Comment by mrhotio** [comment]
Yep, definately don't go fabricating hd logos if the channel doesn't use one...

**Pull request merged**
