### PR TITLE
Some snp.index updates and new Logos

### PR DESCRIPTION
**Pull request by SmoothMC**
A new pull request finaly with working new mdr and new Disney Channel Logos and also some other Logos

thx for merge

### CODE REVIEW

**Comment by mrhotio** [comment]
Is Disney Channel that unreadable on darker skins that it warrants a seperate light version?

**Comment by SmoothMC** [comment]
this are the two main color versions are used by disney channel it self. For example in breaks between shows. There are many other color solutions.
[Logo Variations Disney Channel -> scroll to bottom](https://logos.fandom.com/wiki/Disney_Channel/Logo_Variations
)

When you disagree.
This could be a solution:
default=dark
light=default
white=white

ok?

**Comment by mrhotio** [comment]
I'd rather we just follow the guidelines, instead of making stuff up. Seems europe needs a different logo? @Lexzie @AbuBaniaz what's your take on it?

**Comment by SmoothMC** [comment]
This seems to be  the [international](https://vignette.wikia.nocookie.net/logopedia/images/6/6e/Disney_Channel_2017.svg/revision/latest?cb=20180412093654) Logo since 2017. The information is from this page. [link](https://logos.fandom.com/wiki/Disney_Channel)

**Comment by AbuBaniaz** [comment]
Personally, I'm not too fussed about minor differences between logo used. It doesn't have to be exact and there will always be broadcasters who lag behind. Look at the Boomerang issue. And also as above, they sometimes use different variant.

The picon is only shown while infobar is shown or in channel list or EPG.

Pick one and use it. If logo changed and we didn't change it, then change all variants. It happens quite often that there are default/light/white ones. Someone uploads an updated default/light one, so the old white one remains. Especially when replacing PNG with SVG.

**Pull request merged**
