### PR TITLE
Added logos and tv/radio services for vodafone cable extracted from tvheadend

### PR DESCRIPTION
**Pull request by scheilch**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
We already have following logos:
crimeandinvestigation
crimeandinvestigationhd
beateuhsetv- maybe we can add an SVG HD version?
hgtv- maybe we can add an SVG HD version?
klassik
mdrradiosachsenanhalt

Can you please double check and remove the duplicated logos

**Comment by scheilch** [comment]
How can i check those "Check for faults" by myself?

I am still not ready with all services but wanted to make a pull request to let others participate from these changes. 

I also have a problem with C619_2718_F001_FFFF0000 as is is crime and investigation on vodafone and bio in the original srp file. Which will be chosen if 2 channels have the same id?

I check my logos now and will take the ones you suggested. 
For a svg version of hd channels beateuhse and hgtv it would be nice to get a crash course in inkscape :) Maybe you have some links. 

mdr1radiosachsenanhalt differs from your suggested mdrradiosachsenanhalt as it should be mdr 1 - see also mdr1radiosachsen.default.svg (from repo) and the mdr1radiothuringen.png (from me)
These all are radio channels and they should be named with mdr1
I think the logo mdrradiosachsenanhalt should be removed because the tv channel logo is named like this, For the radio stations of mdr exist special radio logos.

**Comment by Lexzie** [comment]
A lot more logos we already have, only named differently.
Let me check it before anyone commits this.

**Comment by Lexzie** [comment]
> How can i check those "Check for faults" by myself?

Just try to find if a logo already exist (if the channel is on satellite it probably already exists).

 
> I also have a problem with C619_2718_F001_FFFF0000 as is is crime and investigation on vodafone and bio in the original srp file. Which will be chosen if 2 channels have the same id?

Channels cannot have the same ID.
So if there's already a link in srp.index (or a srp link in snp.index), the first on from top to bottom will be shown. That's why new links have to be added on top of srp.index.
Good practice is to delete the old link.

 
> I check my logos now and will take the ones you suggested. For a svg version of hd channels beateuhse and hgtv it would be nice to get a crash course in inkscape :) Maybe you have some links.

[CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)
[Cleaning up SVG metadata](https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata)) 
 

> mdr1radiosachsenanhalt differs from your suggested mdrradiosachsenanhalt as it should be mdr 1 - see also mdr1radiosachsen.default.svg (from repo) and the mdr1radiothuringen.png (from me) These all are radio channels and they should be named with mdr1 I think the logo mdrradiosachsenanhalt should be removed because the tv channel logo is named like this, For the radio stations of mdr exist special radio logos.

Sometime a **logo** is named differently than how the station is named.
This can have different reasons, one is f.e. it's an old name or the logo is used for multiple stations or the same name is already in use for a different logo. This is why **logos** are linked to **station names** (snp.index) and **service references** (srp.index).

`mdr1radiosachsen.default.svg` is the old logo of 'MDR Sachsen'. In theory it should have been deleted.
Because the '1' disappeared in the logo, the naming of the new logo is in fact correct.
The radiostations don't use a logo with an 1 in it, check https://www.mdr.de/radio/index.html
The TV stations don't use the regional name in their logos, so a generic `MDR` logo is correct.

Still checking the logos, f.e. the logo you provide for `Antenne Brandenburg` is an old logo for that station.
The current logo you can see here https://www.antennebrandenburg.de/
The reason you didn't find that logo is that according to the text in the logo it is named `rbbantennebrandenburg` and not `antennebrandenburg`.

**Comment by Lexzie** [comment]
Please stop adding logos we already have.
Add new srp-links on top of srp.index.

**Comment by scheilch** [comment]
I'll close this pull request for maintainig the the pushed code. 

But for today im really tired - so i'll have a look to your instructions tomorrow.

**Pull request closed without merging**
