### PR TITLE
(ROI) rtejunior updates  - fixes #1261

### LINKED ISSUE #1261: ROI channel rtejr - typo and new srp entry
# SNP/SRP entries

**snp.index**
```
rtejunior=rtejunior
```

**srp.index**
```
845_3EA_2174_EEEE0000=rtejunior
```

# Logos

```
![rtejunior default](https://user-images.githubusercontent.com/36491088/210460635-d7412b47-96ad-407a-a358-a4008826b98d.svg)

```

### PR DESCRIPTION
**Pull request by sloxy**
ROI rtejunior updates  - fixes #1261

add rtejunior logo and add new entries

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
We already have the logo. Please add the link to point to it instead of adding an identical logo with a different name

**Comment by AbuBaniaz** [comment]
> We already have the logo. Please add the link to point to it instead of adding an identical logo with a different name

https://github.com/picons/picons/blob/master/build-source/logos/rtejr.default.svg

The SRP link you are adding should point to the existing logo.
Just add the `e` to the existing snp link.  The apostrophe's umlauts were a recent addition to enigma2 picon code.

**Comment by sloxy** [comment]
updated PR.

**Comment by AbuBaniaz** [comment]
> updated PR.

Still need to change the SRP entry you are adding

**Pull request merged**
