### PR TITLE
New logos for polish tv stations

### PR DESCRIPTION
**Pull request by BlazejosP**
I just added various logos for all polish language (but not only) tv stations which are available in that state and outside. This is based on channels available for free-tv in the air and also inside cable tv in Poland and include also small local tv like for example **tvs-suwalki.default.png (TVS local tv from city of Suwałki only available there inside cable tv)**

**srp.index** I added frequencies for free air tv they are standardized in whole country and some available frequencies for cable-tv
**snp.index** I modified some polish tv stations to remove outdated logo and put there an actually one's. I also add this new not available previously channels.

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
filename tv-police is invalid, don't use the '-'.
tvpolice logo is not cropped.
tvp3lodz.black.svg is invalid (background).
What's wrong with our existing tvp3lodz logo's?

etc..

**Review by Lexzie — CHANGES_REQUESTED** [review]
svg's not cleaned (look at the background of the 'HD' letters).
Save them as optimized SVG's: https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

**Review by Lexzie — CHANGES_REQUESTED** [review]
Why delete all those links????

**Comment by Lexzie** [comment]
Too many errors and your changes for srp.index and snp.index will ruin hours of work!

**Comment by Lexzie** [comment]
I realize you have done a lot of work for this, please bring it down in different small pull requests so I can check them.
I will help you, but this is too much at once.

**Comment by Lexzie** [comment]
I downloaded all the logos, I will take care of it.

**Comment by BlazejosP** [comment]
Thanks that you take care about logos that all tv channels available on polish territories and some from outside like belsat and polvision. I checked **tvp3lodz** previous logo was correct I modified this because I done all TVP3 regional stations and forgot that this only one is already done. What do you thing how should I prepare snp and srp to made this acceptable?

**Comment by Lexzie** [comment]
Well, I'm sorry to say, but the majority of the logos you supplied did not meet our criterea.
To keep our repository of good quality I will check them all and correct them.

For some logos I found an svg and that's always preferred above png. (like echo24, inultra).
A lot of your logos were not cropped, like fanklub, lokalna.
You use a `-` in the name of the logo, that's only used when you add a unique identifier if a name already exists.
And your naming is not what is seen in the logo. F.e. you add `tv` when the logo does not say tv (like fanklub, echo24, faktykaliskie, lokalna) and more that I cannot see in the logo, like `ptrtv-slupsk-debica`, in the logo I read `polskatelewizjaregionalna`, so you should name the logo that.
See: https://github.com/picons/picons/blob/master/CONTRIBUTING.md#naming

Some of the `white` logos aren't white.
You add light **and** dark logos. We only support a default logo and if that logo is not visible on a dark background we only add a light logo. If the default is not visible on a light background we add a dark one.
Some of your default logos are perfectly visible on both a dark and a light backgound, so in that case don't add a light or dark logo.

And then logos of bad quality, f.e. fanklub, filmax, htsslubicetv, polvision. I managed to find or make better logos for these. I cannot promise I will be able to do that for all bad quality logos.


This is it for now, be patient, it will take a while before I have all corrected. I do have a normal life too of course...

**Comment by Lexzie** [comment]
> do you thing how should I prepare snp and srp to made this acceptable?

**Don't delete links that have nothing to do with your additions!**

Read the [contribution guidelines](url) on our naming.

**Comment by Lexzie** [comment]
@BlazejosP Just an update: I have not done all the logos yet, patience.
Have you found out yet how to do the updates for snp.index and srp.index?

You could use [the template](https://github.com/picons/picons/issues/new?assignees=&labels=update&projects=&template=add-picons-request.md&title=A+description+of+what+you+are+updating+by+this+request) for supplying the updates?

No need to add the logos.zip, they were already in this PR, unless you have new logos.

**Comment by Lexzie** [comment]
@BlazejosP I am doing a lot of work for you, would you mind and do some effort to supply the links for srp.index and snp.index?
The names of the logos are now:
```
8tvr
belsat
bezpiecznapodroz
dami
echo24
faktykaliskie
fanklub
filmax
htsslubicetv
inultra
lokalnatelewizja
metro
pilskatv
polsatgo
polskieradio24
polskieradiodlazagranicy
polskieradiodwojka
polvision
radiokaszebe
radiokolor
radiorekord
regatv
regionalnatv
tbnpolska
telewizjadamijeleniagora
telewizjagolubdobrzyntv
telewizjakaszuby
telewizjanarew
telewizjaolsztyn
telewizjasudecka
trusotv
tttvtomaszowski
ttvhd
tv4-lichoridas
tv6-lichoridas
tvasta
tvb24
tvchd
tvmaster
tvmorag
tvobiektyw
tvp1
tvp1hd
tvp2
tvp2hd
tvp3
tvp3bialystok
tvp3bydgoszcz
tvp3gdansk
tvp3gorzowwielkopolski
tvp3katowice
tvp3kielce
tvp3krakow
tvp3lodz
tvp3lublin
tvp3olsztyn
tvp3opole
tvp3poznan
tvp3rzeszow
tvp3szczecin
tvp3warszawa
tvp3wroclaw
tvp4k
tvpabc
tvpabc2
tvpalfa
tvpdokument
tvpgo
tvphd
tvphistoria2
tvpkobieta
tvpkultura2
tvpnauka
tvpolice
tvpparlament
tvppolonia
tvpsport
tvpulshd
tvpvod
tvpwilno
tvpworld
tvregionalna
tvrepublikahd
tvstarachowice
tvstelewizjaswietokrzyska
tvsuwalki
tvt
tvtrwam
tvwschod
tvzachod
ultratv4k
vectra
wp
wphd
wtk
xtremetv
zebrratv
zoomtvhd
ztv
```

**Comment by BlazejosP** [comment]
Thank you for your work with logos  @Lexzie   of course I will done this with srp and snp in a couple of days thanks for your effort to improve and correct this according to rules. Hope that next time I will done this correctly and that will don't need.  :)

**Comment by Lexzie** [comment]
I am already thinking of writing some tutorials, but that takes time too.

**Comment by AbuBaniaz** [comment]
Install the missing picons plugin, it ill make your work a lot easier. Otherwise upload your lamedb file and I will run it for you and you can start adding references.

**Comment by BlazejosP** [comment]
Missing files already uploaded under this request [1659][(url](https://github.com/picons/picons/pull/1659))

**Comment by Lexzie** [comment]
I am finally done cleaning and correcting your logos and I am now checking out the links from #1659 
A few questions:
Is it correct that the cable srp's have _0_0_ as network and transponder ID's?

Are you sure that `5209_0_0_FFFF0000=animalplanethd` is the right logo and not `animalplanethd-clivebesle`?

`1E_1_2268_EEEE0000` changed from `atmrozrywka` to `antenahd`?

Are you sure you want to use the old logo for `61AB_0_0_FFFF0000` (bbcearthhd). In the new design BBC does not use an HD logo anymore as far as I know, otherwise make a screenshot with the logo, I'll try to make it.

Are you sure that `7536_0_0_FFFF0000=discoverysciencehd` is the right logo and not `discoverysciencehd-clivebesle`?

Are you sure that `80E9_0_0_FFFF0000=elevensports1` is the right logo and not `elevensports1-thiwunuchu`?

Are you sure that `80EA_0_0_FFFF0000=elevensports2` is the right logo and not `elevensports2-thiwunuchu`?

Are you sure that `80EB_0_0_FFFF0000=elevensports3` is the right logo and not `elevensports3-thiwunuchu`?

Are you sure that `1772_0_0_FFFF0000=elevensports4` is the right logo and not `elevensports4-thiwunuchu`?

Are you sure that `7151_0_0_FFFF0000=investigationdiscovery` is the right logo and not `investigationdiscovery-jusowanusw`?

Are you sure that you want to use the old Polsat HD-logos (polsatsportextrahd and polsatsporthd) instead of the new logos without "HD"?

Are you sure that `84D4_0_0_FFFF0000=sportklubhd` is the right logo and not `sportklubhd-lichoridas`?

**Comment by Lexzie** [comment]
@BlazejosP please answer the questions, so we can wrap this up.

**Comment by BlazejosP** [comment]
Hello sorry that after 3 weeks just was occupied with different issues and I don't checkout there.
Just to answer for your questions?

`Are you sure that 5209_0_0_FFFF0000=animalplanethd is the right logo and not animalplanethd-clivebesle?`
No you have right I'm not certain which logo is used here I have this chanell on my cable-tv but is encoded so can't check and see which logo is actually in use

`1E_1_2268_EEEE0000 changed from atmrozrywka to antenahd?`
Here I'm certain because atm rozrywka stops broadcasting and now instead is here on this frequency in cable tv new channel which is not encoded so I saw this myself

`Are you sure you want to use the old logo for 61AB_0_0_FFFF0000 (bbcearthhd). In the new design BBC does not use an HD logo anymore as far as I know, otherwise make a screenshot with the logo, I'll try to make it.`
I can't also check this channel on my cable-tv is encoded so that my was asumption so is probably better stay with new logo as you proposed

`Are you sure that 7536_0_0_FFFF0000=discoverysciencehd is the right logo and not discoverysciencehd-clivebesle?Are you sure that 80E9_0_0_FFFF0000=elevensports1 is the right logo and not elevensports1-thiwunuchu?Are you sure that 80EA_0_0_FFFF0000=elevensports2 is the right logo and not elevensports2-thiwunuchu?Are you sure that 80EB_0_0_FFFF0000=elevensports3 is the right logo and not elevensports3-thiwunuchu?Are you sure that 1772_0_0_FFFF0000=elevensports4 is the right logo and not elevensports4-thiwunuchu?Are you sure that 7151_0_0_FFFF0000=investigationdiscovery is the right logo and not investigationdiscovery-jusowanusw?
Are you sure that 84D4_0_0_FFFF0000=sportklubhd is the right logo and not sportklubhd-lichoridas`
The same issue that was my assumption but I haven't access to this stations they are encoded but I know this frequencies from my cablr-tv

`Are you sure that you want to use the old Polsat HD-logos (polsatsportextrahd and polsatsporthd) instead of the new logos without "HD"?`
Sorry but Polsat sport extra is also encoded so I know only frequency but can't check that on picture but my quess will be that they us also new logos

**Comment by Lexzie** [comment]
Thanks, I will submit it later and use the logos as already confirmed on satellite that they use these logos.

**Comment by Lexzie** [comment]
There's still one thing...

I can't link the name `tvt` to the logo `tvt` because we have already a link which links that name:
`tvt=tvtourism`.

The solution to that is that we link the service reference of the Polish TVT to the tvt logo.
So, if you supply the service reference of tvt I could add that link.

For the rest, let me know how it turned out and if something is still missing.

**Comment by BlazejosP** [comment]
`I can't link the name tvt to the logo tvt because we have already a link which links that name:
tvt=tvtourism.`

Hello I can't provide you frequency for TVT because haven't this channel in air TV nor in cable TV. Is broadcasted in polish region of Silesia only. But is broadcasted on specific regional MUX L2 there in the air and in 6 different cable tv there. So i spouse is on many various frequencies one for MUX from air and various different in cable tv's. So meaby is better to rename picture of this tvstation logo to something like tvtslask.default.png (from geographical region) or tvtrybnik.default.png (from city of Rybnik where are their studios) ? and then will be no conflict with `tvturism` from different country.

I also found similar problem with tv6 in Poland inside snp.index
Polish TV6 is using for both name of channel color new logo 
```
tv6=tv6-lichoridas
```
There should be also `tv6hd=tv6-lichoridas` because name with hd is used by cable tv

but inside the same file Algerie channel 6 us this
```
tv6hd=algerie6
```
so I don't know how resolve this conflict they use the same description for HD chanell `tv6hd`

I found that you solved this by adding 
`84D9_0_0_FFFF0000=tv6-lichoridas`
but his polish channel is on airtv nationwide on various frequencies depending of region and also in all cabletv so is on many frequencies I myself found this tv6 on two different one from airtv and one from cable so this conflict with algerie6 is a little bit problematic?

**Comment by Lexzie** [comment]
Renaming the logo is not necessary and won't solve this. The logos have different names: `tvt` and `tvtourism`.

You found out yourself that if different stations use the same name we have to use the service reference(s) of one if them to link to the correct logo in snp index:

> I also found similar problem with tv6 in Poland inside snp.index Polish TV6 is using for both name of channel color new logo
> 
> ```
> tv6=tv6-lichoridas
> ```
> 
> There should be also `tv6hd=tv6-lichoridas` because name with hd is used by cable tv
> 
> but inside the same file Algerie channel 6 us this
> 
> ```
> tv6hd=algerie6
> ```
> I found that you solved this by adding `84D9_0_0_FFFF0000=tv6-lichoridas` but his polish channel is on airtv nationwide on various frequencies depending of region and also in all cabletv so is on many frequencies I myself found this tv6 on two different one from airtv and one from cable so this conflict with algerie6 is a little bit problematic?

Another frequency doesn't necessarily mean a different service reference.
Ad we don't need the frequency, just the service reference.

If you experience the wrong logo on a Enigma2 receiver you can simply find the service reference in the menu of the receiver.
If you don't know how, just ask. I will explain it to you.

Don't bother about other regions and cable-providers which you have no access to, you won't see the logo anyway.

**Comment by Lexzie** [comment]
> For the rest, let me know how it turned out and if something is still missing.

How about this?

**Comment by BlazejosP** [comment]
Thanks probably best solution to fix this manually if with tv6HD algerie. Thank you for taking care for all this logos and made this add-on possible. Really great work :+1: . Next time when I upload something I will try do this in small number and according to rules.

**Comment by Lexzie** [comment]
Why do you want to fix that manually while we have the automatic solution for you?
If you use a Enigma2 receiver (f.e. with OpenPLi) go in the menu to Information > Service and write down the service reference.
Or install a settings editor like [Dreamset](https://www.dreamset-editor.com/index.php?dreamset-download.htm). Read out the settings and store in somewhere on your computer.
From that folder send me the file `lamedb`.
Or find the file on your receiver with [DCC](https://www.linuxsat-support.com/filebase/file/138-dcc-dreambox-control-center-by-bernyr/), [WinSCP](https://winscp.net/eng/index.php) or Windows Explorer. It's in the folder `/etc/enigma2`

**Pull request closed without merging**
