### PR TITLE
NDR Schlager

### PR DESCRIPTION
**Pull request by Varkentjes**

### CODE REVIEW

**Comment by Lexzie** [comment]
I'd like to comment on this.
You have done a good job and it is probably not a bad idea to make the `NDR` in the `light` logo lightblue.
But all the other NDR radio logos we already have it is white. Logically they all would be the same format, unless another colour is used on the website f.e. (and for TV stations on the screen in leaders f.e.).

**Comment by Varkentjes** [comment]
I had also seen that the existing `light` logos are white. My proposal is to make the other logos also in `light` blue. But I wanted to do that in a separate PR if we agree.

(p.s. I already have the new blue logos ready)

**Comment by Lexzie** [comment]
Well, I think if you already have done that we can do that.
I could not find examples of light logos on the website of NDR, so there's no reference.

**Comment by Varkentjes** [comment]
#897

**Pull request merged**
