### PR TITLE
Qmusic top40

### PR DESCRIPTION
**Pull request by Varkentjes**
Because I was not that satisfied with the logos I made earlier, I tried to design a new one. I found a way with Inkscape to design an SVG from an existing image. So hereby 2 new logos, a default and a light version in SVG.

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
Very, very nice. But you first have to save them as 'Optimized SVG'.
The guide is overhere: https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

**Comment by Varkentjes** [comment]
Done. Also 2 previously made logos optimised.

**Comment by Lexzie** [comment]
I trust this will be okay. No time to check now.
I am happy my radio-list gets more and more filled with picons. :-)

**Comment by Varkentjes** [comment]
I just tested them in my STB and everything seems to be fine. Thank you Lexzie, good to hear the logos are so welcome. A new batch of logos is on the way.

**Pull request merged**
