### PR TITLE
4ever(49)radio

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by Dream1975** [comment]
Hello Lexzie, firstly I hope you don't mind contacting you directly but can you help me with something. I know you maintain the Ziggo picons (of which I am very grateful) but there are 3 in my list that have no picon (likely because these are local TV stations not in your area). Can you help me how I can make enclosed png's in your style and add them to the repository?

90TV-default
RTV-Tempo-Soest default
Lokaal
DBTV-default

**Comment by Lexzie** [comment]
No I don't mind and I didn't know these stations exist.
Probably because they have no stream on the internet or that they have changed recently. I haven't checked my list of Dutch local stations recently.
I will add them later but can you provide the srp and snp-links?

By the way, the correct way of requests like this is to submit an issue. We even have a template when you click on New Issue on how to submit an Issue.
Please use that the next time or check it out how you can provide the links to me.
Websites of the channels would be nice too.

**Comment by Lexzie** [comment]
I already checked out 'Tempo Soest' since I could not believe that a local station is that old.
I was right, this logo is from a cycling club (RTV = Ren en Toer vereniging).
So please provide the right logo, make a screenshot of it and/or provide the url of their website.

**Comment by Dream1975** [comment]
Oops indeed, I searched for RTV Soest and this one came up. It seems it is the cable newspaper for Radio Soest so it has no own TV logo https://www.radiosoest.nl/

logo

For the servicerefs:
Regio90TV
1:0:1:1843:C74:600:FFFF0000:0:0:0

RTV Soest
1:0:1:1846:C74:600:FFFF0000:0:0:0

DBTV
1:0:19:1845:C74:600:FFFF0000:0:0:0

**Comment by Lexzie** [comment]
Allright, Are you sure the 'kabelkrant' is using the _radio_ logo?
I can't find a stream of it so I have no way of checking that.
You can make screenshots f.e. in the webinterface of your Enigma2-receiver, just go to `https://<ip-address of your receiver>`. You can find the IP-address in the menu of your receiver.

We already have the logos for `Regio 90 TV` and `Radio Soest`, so no need to search for those.
Found something of the so called 'De Bunschoter', need to search for a better logo.
Probably not before this evening.

By the way: I don't mind but make sure how to submit these requests.
Read the [contribution guidelines](https://github.com/picons/picons/blob/master/CONTRIBUTING.md) for later requests.

**Comment by Dream1975** [comment]
Again thank you very much. Please find enclosed some live screenshots I just made

**Comment by Lexzie** [comment]
Can you make a screenshot with logo of DBTV too?

**Comment by Lexzie** [comment]
Can't find the DBTV logo without background that is (a lot) bigger than 200 pixels in height.

**Comment by Dream1975** [comment]
Hello again, at the moment I'm not home but their website is https://www.debunschoter-online.nl/

Maybe you can use the logo on top of that page? If not please let me know and I'll make a screenshot tomorrow evening.
Bunschoter

**Comment by Dream1975** [comment]
One additional (and final, I promise) question, would it be possible to also add the Tomorrowland logo (if it is in the repository I can edit the snp.index myself for the "One World Radio - Tomorrowland" radio stream). It is to be expected the TV station will also restart in the near future after testing this summer (https://www-broadcastmagazine-nl.translate.goog/facilitair/dutchess-media-one-world-tv/?_x_tr_sl=nl&_x_tr_tl=en&_x_tr_hl=nl&_x_tr_pto=wapp) and then the same picon can be used. 
Tomorrowland

**Comment by Lexzie** [comment]
Yes we can add it, but only if you don't edit the snp.index yourself but let us do it in the repository, so everyone benefits from it.
So, as soon as you know the links, let us know.

**Comment by Lexzie** [comment]
> Hello again, at the moment I'm not home but their website is https://www.debunschoter-online.nl/
> 
> Maybe you can use the logo on top of that page? If not please let me know and I'll make a screenshot tomorrow evening.
> Bunschoter
> 

The logo on their website is too small.
I need the screenshot to see what they exactly use on the channel.

Maybe you can mail them and ask for a vector-logo or a bitmap-logo with transparent background of at least 800 pixels?

**Comment by Dream1975** [comment]
"Yes we can add it, but only if you don't edit the snp.index yourself but let us do it in the repository, so everyone benefits from it.
So, as soon as you know the links, let us know."
I ment in the repository (I've done this before when names were changed). Editing the snp I understand, making the right Picons is more difficult for me, thus my requests (I am really glad you help me with that). But in the channel list the name is "
One World Radio - Tomorrowland" so if you want to edit the snp you can use this name.

The channel itself is a cable newspaper with a very small logo on the right upside of the screen (and unfortunately there is no page displaying the logo full screen). I have mailed them requesting for a logo. If they get back to me I'll let you know here (but in the meantime leave it as is for this particular logo one missing isn't the end of the world.

Ps. I also found this one on the internet (it's high resolution), maybe that can be something if not we'll have to wait for a response
Bunschoter

**Comment by Lexzie** [comment]
If you can do the changes yourself, please do so! 👍🏻 

I hope they can mail you the logo, these are still too small or don't have a transparent background.

What I want to know of the logo onscreen is:
Is the logo in the right upperside of the screen just the logo?

Like this:
afbeelding

or is there also text besides the logo?

F.e. like this:
afbeelding

On YouTube I see this logo, is that an old one?
afbeelding


About the One World Radio / Tomorrowland logo, I will look into it later. I know I've been searching for a decent logo in the past but could not find it. Maybe this time better luck.

**Comment by Dream1975** [comment]
At the moment I am from home so can't make the screenprint, but it is exactly like this one (without "samen communiceren", but with "de bunschoter" text)

193026481-7e2cea39-f553-4f5c-b782-c98a0b7f2193

**Comment by Lexzie** [comment]
Well, we still need that logo in vector-format (f.e. svg) or one on transparent background with large resolution.
I can probably make the text myself.

**Comment by Lexzie** [comment]
I already had a logo for [One World Radio](https://www.tomorrowland.com/home/radio):

oneworldradio default

I will upload it later with 
```
oneworldradio=oneworldradio
```

Now I have to know what logo they are going to use on the television station.

**Comment by Lexzie** [comment]
I thought we already had a good logo of Radio Soest, but unfortunately I can't find one.

**Comment by Lexzie** [comment]
One World Radio logo and link added.
Regio 90 TV links added.

**Comment by Dream1975** [comment]
Thank you very much. If I get a reply on my mail I'll let it know here. For now wishing you a nice weekend

**Pull request merged**
