### PR TITLE
Add YU Planet and links

### PR DESCRIPTION
**Pull request by Lexzie**
Seems that I can't commit anymore like before and I have to make a branch?

When I want to commit to master I get this error:
afbeelding

### CODE REVIEW

**Comment by mrhotio** [comment]
Yes, that was the idea, but I thought it was too restrictive, so I thought I rolled it back, but like it's acting now was the desired outcome.....you were able to merge after the checks passed right?

**Comment by Lexzie** [comment]
Yes, I guess it went well, but I was suprised I have to make a branch, then push the branch myself and then squased and merged the branch myself.
Now I still have to delete the branch?

**Comment by mrhotio** [comment]
Yes, you can delete the branch or keep one branch called after your name that you keep up2date, however you like

**Comment by Lexzie** [comment]
Allright, checks via https://cloud.drone.io/picons/picons are not done anymore?

**Comment by mrhotio** [comment]
no, they are done by GitHub Actions now, just as the builds

**Comment by Lexzie** [comment]
Well, this is all I get:
afbeelding

**Pull request merged**
