### PR TITLE
New Atreseries HD channel

### PR DESCRIPTION
**Pull request by jlazkano**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Our project works like this
Link + logo = picon

You provided a link, but we do not have an atrserieshd logo. Do you have a HD logo?

**Comment by jlazkano** [comment]
Hello,

Sorry, here is the logo: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/atreseries_HD.png

Just rename to atreseries.png.

I can not upload the file to the repository.

Regards.

**Comment by AbuBaniaz** [comment]
>Just rename to atreseries.png

No, we add the hd logo and add correct link to it

**Comment by Lexzie** [comment]
Looks like the current atresseries logo is okay and a svg. I guess we can make the hd logo in svg as well?

**Comment by Lexzie** [comment]
I made the HD logo and added it, added snp-links. Without service reference can't add the srp-link.

**Pull request closed without merging**
