### PR TITLE
Sunrise UPC Switzerland

### PR DESCRIPTION
**Pull request by 4l3x2k**
Link existing logos to service name and reference.

### CODE REVIEW

**Review by Lexzie — CHANGES_REQUESTED** [review]
The logo for RMC Sport Access 1 is not the same as RMC Sport 1.
Example: 
https://static.wikia.nocookie.net/logopedia/images/d/d3/RMC_SPORT_1_ACCESS_2018_OFFICEL.png/revision/latest?cb=20191103072417
Please upload the correct logo and assign that to `rmcsportacces1hd` (acces with one 's'?)
Hint: Use [the logo from Logopedia](https://logos.fandom.com/wiki/RMC_Sport_1), but please remove the empty space on the left.

`junior` is already assigned to `radiojunior-uowrefreja`, please use a srp-link.

These links already exist, no need to add them twice:
```
rts1hd=rtsun
rts2hd=rtsdeux
```

France Télévision don't use HD-logos anymore, so `france2hd` is addigned to `france2`, and please assign `france4hd` and `france5hd` to `france3` resp. `france5`.

The same remarks as above for:
```
1BDA_E0_1_FFFF0000=rmcsport1
2335_E_1_FFFF0000=france2hd
256C_1A_1_FFFF0000=france3hd
253D_C_1_FFFF0000=france4hd
253E_C_1_FFFF0000=france5hd
```

Please check these things before making the Pull Request, so we don't have to do that.

**Comment by 4l3x2k** [comment]
Hi @Lexzie,

thank you for feedback. I hope that all review comments are correct in the new commit.

The RMC Sport Access 1 logo comes with part 2 where all new logos are in.

Are you sure about
```
rts1hd=rtsun
rts2hd=rtsdeux
```
?
Both channels are currently linked to rts1 and rts2, but when I look at these logos they read PTC 1 and PTC 2.

**Comment by AbuBaniaz** [comment]
We currently have these entries, so one needs to be removed.

```
rtsh1=rtsh1
rtsh1=rtsh1hd
```

Where there is an existing SNP name shared by a different channel that needs to point to a different logo, eg ITV in the UK (before change to ITV1) and ITV on 13e, the srp code has to be used for one of them.  We don't have two different `itv=`  entries

**Comment by Lexzie** [comment]
> Hi @Lexzie,
> 
> thank you for feedback. I hope that all review comments are correct in the new commit.
> 
> The RMC Sport Access 1 logo comes with part 2 where all new logos are in.
> 
> Are you sure about
> 
> ```
> rts1hd=rtsun
> rts2hd=rtsdeux
> ```
> 
> ? Both channels are currently linked to rts1 and rts2, but when I look at these logos they read PTC 1 and PTC 2.

You did not add the srp-links in snp.index like I suggested.

The same for `rts1hd` and `rts2hs`, you were right they link to the wrong logos.

So please (also) add to snp.index:
```
93_7E_1_FFFF0000=junior
2350_F_1_FFFF0000=rtsun
2351_10_1_FFFF0000=rtsdeux
```

**Comment by 4l3x2k** [comment]
Now I see why there are sometimes srp links in the snp.index.

I hope everything is in place now. Sorry for this, but it is not as easy as it look like without practice.

**Comment by Lexzie** [comment]
Did you read the contrubution guidelines?
We also have a wiki on [cleaning the svg's](https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata) if you're going to add them.

Next time the index in alphabetic order (by logoname) please.

**Pull request merged**
