### PR TITLE
UK channel ITV rebranded as ITV1 so changes needed in snp.index

### PR DESCRIPTION
**Pull request by BrianG61UK**
Both all old and all new names will get the new icons @AbuBaniaz added.
This is because old names may remain in use, for example, due to Auto Bouquet Maker.

### CODE REVIEW

**Comment by BrianG61UK** [comment]
I messed up when trying to merge all my changes in to one commit.
If you wish, you can close this, and I'll do it again as a single commit.

**Comment by AbuBaniaz** [comment]
As far as I am aware, the ABM renames do not add the "1".  I will double check later. I don't see the benefits in your pull request. The Freesat tables have anomalies too.

**Comment by AbuBaniaz** [comment]
There is no need for these links. If I have understood it incorrectly, please post screenshots. 

If you are going to update a request to change the ITV renames on ABM, don't forget the Freesat provider. The renames do not tally.

**Comment by BrianG61UK** [comment]
@AbuBaniaz Well the Picons and ABM both need to be changed. I thought I had them both working together correctly on my box and just chose to submit the changes to Picons first since they can be done while still maintaining compatibility with the current unchanged ABM. But maybe there are mistakes in the Freesat parts.

Picons: as this PR.
ABM Freesat: https://github.com/oe-alliance/AutoBouquetsMaker/compare/master...BrianG61UK:AutoBouquetsMaker:ITVbecomesITV1
ABM Sky: https://github.com/oe-alliance/AutoBouquetsMaker/compare/master...BrianG61UK:AutoBouquetsMaker:ITVisnowITV1

**Comment by AbuBaniaz** [comment]
I am going to leave those ABM pull request for other contributors. We were using one set of names, when they were changed to to another source of names, the Freesat ones were not changed. You therefore get a mismatch of names. You see this when Sky and Freesat are run together.

**Comment by BrianG61UK** [comment]
@AbuBaniaz I don't fully understand about the names. Aren't the Sky and Freesat bouquets generated by ABM completely separate?
My proposed ABM changes are not pull requests yet, just waiting in my repository.

**Comment by AbuBaniaz** [comment]
They are separate providers, so separate bouquets. But service names go in lamedb, whatever the bouquet. One provider calls it one, another calls it something else, yet another on the stream.  You will probably get the comment `Why would someone run Freesat and Sky together?` Anyway, best we talk about picons here.

**Pull request closed without merging**
