### PR TITLE
Revert "Lx classics, radio nostalgia, social radio"

### PR DESCRIPTION
**Pull request by Lexzie**
Reverts picons/picons#297

### CODE REVIEW

**Comment by Lexzie** [comment]
What a mess. I tried to replace two logos in PR #297 via Github Desktop but that didn't work. So looks like I have to revert this first?

**Comment by Lexzie** [comment]
By the way: Still doing a great job @Varkentjes , but pay attention to the quality of the work.
Try to find better logos or check if no pixels are left over after removing the background.
I find it the easiest to add a extra layer behind the logo, fill it with black or white (depending if the removed background was light or dark) and you can easily see if there are pixels leftover, or if the edge of the logo needs some cleaning (f.e. in the LX classics logo).

**Comment by Varkentjes** [comment]
@Lexzie you are totally right. I had to notice this before uploading. My apologies for making a mess of this, but I'm still on a learning curve and mistakes has to happen to become better. Next time I'll take more attention to prevent this from happening again.

I think you did fix the whole issue or is there something leftover for me?

BTW what is the source of the logo for Radio Nostalgia? I did a new search on Google but can't find the same logo you did  :-(

**Comment by Lexzie** [comment]
Cleaning was easy, so yes it's all done. But frrl free to keep trying with new logos.
Don't know the source anymore, found it also via Google.

**Pull request merged**
